info:
  namespace: ec_elitearmors
armors_rendering:
  ecrubyarmor_darkbrown:
    color: '#5cec42'
    layer_1: armor/ec_elitearmorsvol6/ecrubyarmor_darkbrown
    layer_2: armor/ec_elitearmorsvol6/ecrubyarmor_darkbrown_2
    emissive_1: armor/ec_elitearmorsvol6/ecrubyarmore_1
    emissive_2: armor/ec_elitearmorsvol6/ecrubyarmore_2
    use_color: false
  eclightknightarmor_darkbrown:
    color: '#66f6c4'
    layer_1: armor/ec_elitearmorsvol6/eclightknightarmor_darkbrown
    layer_2: armor/ec_elitearmorsvol6/eclightknightarmor_darkbrown_2
    emissive_1: armor/ec_elitearmorsvol6/eclightknightarmore_1
    emissive_2: armor/ec_elitearmorsvol6/eclightknightarmore_2
    use_color: false
  ecbluemecharmor_darkbrown:
    color: '#87dfcd'
    layer_1: armor/ec_elitearmorsvol6/ecbluemecharmor_darkbrown
    layer_2: armor/ec_elitearmorsvol6/ecbluemecharmor_darkbrown_2
    emissive_1: armor/ec_elitearmorsvol6/ecbluemecharmore_1
    emissive_2: armor/ec_elitearmorsvol6/ecbluemecharmore_2
    use_color: false
  eclavabeastarmor_darkbrown:
    color: '#28a805'
    layer_1: armor/ec_elitearmorsvol6/eclavabeastarmor_darkbrown
    layer_2: armor/ec_elitearmorsvol6/eclavabeastarmor_darkbrown_2
    emissive_1: armor/ec_elitearmorsvol6/eclavabeastarmore_1
    emissive_2: armor/ec_elitearmorsvol6/eclavabeastarmore_2
    use_color: false
equipments:
  ecrubyarmor_darkbrown:
    layer_1: armor/ec_elitearmorsvol6/ecrubyarmor_darkbrown
    layer_2: armor/ec_elitearmorsvol6/ecrubyarmor_darkbrown_2
  eclightknightarmor_darkbrown:
    layer_1: armor/ec_elitearmorsvol6/eclightknightarmor_darkbrown
    layer_2: armor/ec_elitearmorsvol6/eclightknightarmor_darkbrown_2
  ecbluemecharmor_darkbrown:
    layer_1: armor/ec_elitearmorsvol6/ecbluemecharmor_darkbrown
    layer_2: armor/ec_elitearmorsvol6/ecbluemecharmor_darkbrown_2
  eclavabeastarmor_darkbrown:
    layer_1: armor/ec_elitearmorsvol6/eclavabeastarmor_darkbrown
    layer_2: armor/ec_elitearmorsvol6/eclavabeastarmor_darkbrown_2
items:
  ecrubychest_darkbrown:
    display_name: Ruby Chestplate (darkbrown)
    resource:
      model_id: 2544
      model_path: auto_generated/ecrubychest_darkbrown
      generate: false
      textures:
      - item/ec_elitearmorsvol6/ecrubychest_darkbrown.png
      material: LEATHER_CHESTPLATE
    durability:
      max_custom_durability: 602
    equipment:
      id: ecrubyarmor_darkbrown
      legacy_armor_rendering_id: ecrubyarmor_darkbrown
      slot: CHEST
      slot_attribute_modifiers:
        armor: 7
        armorToughness: 3
  ecrubyhelmet_darkbrown:
    display_name: Ruby Helmet (darkbrown)
    resource:
      model_id: 2545
      model_path: auto_generated/ecrubyhelmet_darkbrown
      generate: false
      material: LEATHER_HELMET
    durability:
      max_custom_durability: 602
    equipment:
      id: ecrubyarmor_darkbrown
      legacy_armor_rendering_id: ecrubyarmor_darkbrown
      slot: HEAD
      slot_attribute_modifiers:
        armor: 4
        armorToughness: 3
  ecrubylegs_darkbrown:
    display_name: Ruby Leggings (darkbrown)
    resource:
      model_id: 2546
      model_path: auto_generated/ecrubylegs_darkbrown
      generate: false
      material: LEATHER_LEGGINGS
    durability:
      max_custom_durability: 602
    equipment:
      id: ecrubyarmor_darkbrown
      legacy_armor_rendering_id: ecrubyarmor_darkbrown
      slot: LEGS
      slot_attribute_modifiers:
        armor: 6
        armorToughness: 3
  ecrubyboots_darkbrown:
    display_name: Ruby Boots (darkbrown)
    resource:
      model_id: 2543
      model_path: auto_generated/ecrubyboots_darkbrown
      generate: false
      textures:
      - item/ec_elitearmorsvol6/ecrubyboots_darkbrown.png
      material: LEATHER_BOOTS
    durability:
      max_custom_durability: 602
    equipment:
      id: ecrubyarmor_darkbrown
      legacy_armor_rendering_id: ecrubyarmor_darkbrown
      slot: FEET
      slot_attribute_modifiers:
        armor: 4
        armorToughness: 3
  eclightknightchest_darkbrown:
    display_name: Lightknight Chestplate (darkbrown)
    resource:
      model_id: 2540
      model_path: auto_generated/eclightknightchest_darkbrown
      generate: false
      textures:
      - item/ec_elitearmorsvol6/eclightknightchest_darkbrown.png
      material: LEATHER_CHESTPLATE
    durability:
      max_custom_durability: 602
    equipment:
      id: eclightknightarmor_darkbrown
      legacy_armor_rendering_id: eclightknightarmor_darkbrown
      slot: CHEST
      slot_attribute_modifiers:
        armor: 7
        armorToughness: 3
  eclightknighthelmet_darkbrown:
    display_name: Lightknight Helmet (darkbrown)
    resource:
      model_id: 2541
      model_path: auto_generated/eclightknighthelmet_darkbrown
      generate: false
      textures:
      - item/ec_elitearmorsvol6/eclightknighthelmet_darkbrown.png
      material: LEATHER_HELMET
    durability:
      max_custom_durability: 602
    equipment:
      id: eclightknightarmor_darkbrown
      legacy_armor_rendering_id: eclightknightarmor_darkbrown
      slot: HEAD
      slot_attribute_modifiers:
        armor: 4
        armorToughness: 3
  eclightknightlegs_darkbrown:
    display_name: Lightknight Leggings (darkbrown)
    resource:
      model_id: 2542
      model_path: auto_generated/eclightknightlegs_darkbrown
      generate: false
      textures:
      - item/ec_elitearmorsvol6/eclightknightleggings_darkbrown.png
      material: LEATHER_LEGGINGS
    durability:
      max_custom_durability: 602
    equipment:
      id: eclightknightarmor_darkbrown
      legacy_armor_rendering_id: eclightknightarmor_darkbrown
      slot: LEGS
      slot_attribute_modifiers:
        armor: 6
        armorToughness: 3
  eclightknightboots_darkbrown:
    display_name: Lightknight Boots (darkbrown)
    resource:
      model_id: 2539
      model_path: auto_generated/eclightknightboots_darkbrown
      generate: false
      textures:
      - item/ec_elitearmorsvol6/eclightknightboots_darkbrown.png
      material: LEATHER_BOOTS
    durability:
      max_custom_durability: 602
    equipment:
      id: eclightknightarmor_darkbrown
      legacy_armor_rendering_id: eclightknightarmor_darkbrown
      slot: FEET
      slot_attribute_modifiers:
        armor: 4
        armorToughness: 3
  ecbluemechchest_darkbrown:
    display_name: Bluemech Chestplate (darkbrown)
    resource:
      model_id: 2532
      model_path: auto_generated/ecbluemechchest_darkbrown
      generate: false
      textures:
      - item/ec_elitearmorsvol6/ecbluemechchest_darkbrown.png
      material: LEATHER_CHESTPLATE
    durability:
      max_custom_durability: 602
    equipment:
      id: ecbluemecharmor_darkbrown
      legacy_armor_rendering_id: ecbluemecharmor_darkbrown
      slot: CHEST
      slot_attribute_modifiers:
        armor: 7
        armorToughness: 3
  ecbluemechhelmet_darkbrown:
    display_name: Bluemech Helmet (darkbrown)
    resource:
      model_id: 2533
      model_path: auto_generated/ecbluemechhelmet_darkbrown
      generate: false
      textures:
      - item/ec_elitearmorsvol6/ecbluemechhelmet_darkbrown.png
      material: LEATHER_HELMET
    durability:
      max_custom_durability: 602
    equipment:
      id: ecbluemecharmor_darkbrown
      legacy_armor_rendering_id: ecbluemecharmor_darkbrown
      slot: HEAD
      slot_attribute_modifiers:
        armor: 4
        armorToughness: 3
  ecbluemechlegs_darkbrown:
    display_name: Bluemech Leggings (darkbrown)
    resource:
      model_id: 2534
      model_path: auto_generated/ecbluemechlegs_darkbrown
      generate: false
      textures:
      - item/ec_elitearmorsvol6/ecbluemechleggings_darkbrown.png
      material: LEATHER_LEGGINGS
    durability:
      max_custom_durability: 602
    equipment:
      id: ecbluemecharmor_darkbrown
      legacy_armor_rendering_id: ecbluemecharmor_darkbrown
      slot: LEGS
      slot_attribute_modifiers:
        armor: 6
        armorToughness: 3
  ecbluemechboots_darkbrown:
    display_name: Bluemech Boots (darkbrown)
    resource:
      model_id: 2531
      model_path: auto_generated/ecbluemechboots_darkbrown
      generate: false
      textures:
      - item/ec_elitearmorsvol6/ecbluemechboots_darkbrown.png
      material: LEATHER_BOOTS
    durability:
      max_custom_durability: 602
    equipment:
      id: ecbluemecharmor_darkbrown
      legacy_armor_rendering_id: ecbluemecharmor_darkbrown
      slot: FEET
      slot_attribute_modifiers:
        armor: 4
        armorToughness: 3
  eclavabeastchest_darkbrown:
    display_name: Lavabeast Chestplate (darkbrown)
    resource:
      model_id: 2536
      model_path: auto_generated/eclavabeastchest_darkbrown
      generate: false
      textures:
      - item/ec_elitearmorsvol6/eclavabeastchest_darkbrown.png
      material: LEATHER_CHESTPLATE
    durability:
      max_custom_durability: 602
    equipment:
      id: eclavabeastarmor_darkbrown
      legacy_armor_rendering_id: eclavabeastarmor_darkbrown
      slot: CHEST
      slot_attribute_modifiers:
        armor: 7
        armorToughness: 3
  eclavabeasthelmet_darkbrown:
    display_name: Lavabeast Helmet (darkbrown)
    resource:
      model_id: 2537
      model_path: auto_generated/eclavabeasthelmet_darkbrown
      generate: false
      textures:
      - item/ec_elitearmorsvol6/eclavabeasthelmet_darkbrown.png
      material: LEATHER_HELMET
    durability:
      max_custom_durability: 602
    equipment:
      id: eclavabeastarmor_darkbrown
      legacy_armor_rendering_id: eclavabeastarmor_darkbrown
      slot: HEAD
      slot_attribute_modifiers:
        armor: 4
        armorToughness: 3
  eclavabeastlegs_darkbrown:
    display_name: Lavabeast Leggings (darkbrown)
    resource:
      model_id: 2538
      model_path: auto_generated/eclavabeastlegs_darkbrown
      generate: false
      textures:
      - item/ec_elitearmorsvol6/eclavabeastleggings_darkbrown.png
      material: LEATHER_LEGGINGS
    durability:
      max_custom_durability: 602
    equipment:
      id: eclavabeastarmor_darkbrown
      legacy_armor_rendering_id: eclavabeastarmor_darkbrown
      slot: LEGS
      slot_attribute_modifiers:
        armor: 6
        armorToughness: 3
  eclavabeastboots_darkbrown:
    display_name: Lavabeast Boots (darkbrown)
    resource:
      model_id: 2535
      model_path: auto_generated/eclavabeastboots_darkbrown
      generate: false
      textures:
      - item/ec_elitearmorsvol6/eclavabeastboots_darkbrown.png
      material: LEATHER_BOOTS
    durability:
      max_custom_durability: 602
    equipment:
      id: eclavabeastarmor_darkbrown
      legacy_armor_rendering_id: eclavabeastarmor_darkbrown
      slot: FEET
      slot_attribute_modifiers:
        armor: 4
        armorToughness: 3
