info:
  namespace: ec_elitearmors
armors_rendering:
  ecrubyarmor_lightgray:
    color: '#5cec32'
    layer_1: armor/ec_elitearmorsvol6/ecrubyarmor_lightgray
    layer_2: armor/ec_elitearmorsvol6/ecrubyarmor_lightgray_2
    emissive_1: armor/ec_elitearmorsvol6/ecrubyarmore_1
    emissive_2: armor/ec_elitearmorsvol6/ecrubyarmore_2
    use_color: false
  eclightknightarmor_lightgray:
    color: '#66f6b4'
    layer_1: armor/ec_elitearmorsvol6/eclightknightarmor_lightgray
    layer_2: armor/ec_elitearmorsvol6/eclightknightarmor_lightgray_2
    emissive_1: armor/ec_elitearmorsvol6/eclightknightarmore_1
    emissive_2: armor/ec_elitearmorsvol6/eclightknightarmore_2
    use_color: false
  ecbluemecharmor_lightgray:
    color: '#87dfbd'
    layer_1: armor/ec_elitearmorsvol6/ecbluemecharmor_lightgray
    layer_2: armor/ec_elitearmorsvol6/ecbluemecharmor_lightgray_2
    emissive_1: armor/ec_elitearmorsvol6/ecbluemecharmore_1
    emissive_2: armor/ec_elitearmorsvol6/ecbluemecharmore_2
    use_color: false
  eclavabeastarmor_lightgray:
    color: '#28a7f5'
    layer_1: armor/ec_elitearmorsvol6/eclavabeastarmor_lightgray
    layer_2: armor/ec_elitearmorsvol6/eclavabeastarmor_lightgray_2
    emissive_1: armor/ec_elitearmorsvol6/eclavabeastarmore_1
    emissive_2: armor/ec_elitearmorsvol6/eclavabeastarmore_2
    use_color: false
equipments:
  ecrubyarmor_lightgray:
    layer_1: armor/ec_elitearmorsvol6/ecrubyarmor_lightgray
    layer_2: armor/ec_elitearmorsvol6/ecrubyarmor_lightgray_2
  eclightknightarmor_lightgray:
    layer_1: armor/ec_elitearmorsvol6/eclightknightarmor_lightgray
    layer_2: armor/ec_elitearmorsvol6/eclightknightarmor_lightgray_2
  ecbluemecharmor_lightgray:
    layer_1: armor/ec_elitearmorsvol6/ecbluemecharmor_lightgray
    layer_2: armor/ec_elitearmorsvol6/ecbluemecharmor_lightgray_2
  eclavabeastarmor_lightgray:
    layer_1: armor/ec_elitearmorsvol6/eclavabeastarmor_lightgray
    layer_2: armor/ec_elitearmorsvol6/eclavabeastarmor_lightgray_2
items:
  ecrubychest_lightgray:
    display_name: Ruby Chestplate (lightgray)
    resource:
      model_id: 2368
      model_path: auto_generated/ecrubychest_lightgray
      generate: false
      textures:
      - item/ec_elitearmorsvol6/ecrubychest_lightgray.png
      material: LEATHER_CHESTPLATE
    durability:
      max_custom_durability: 602
    equipment:
      id: ecrubyarmor_lightgray
      legacy_armor_rendering_id: ecrubyarmor_lightgray
      slot: CHEST
      slot_attribute_modifiers:
        armor: 7
        armorToughness: 3
  ecrubyhelmet_lightgray:
    display_name: Ruby Helmet (lightgray)
    resource:
      model_id: 2369
      model_path: auto_generated/ecrubyhelmet_lightgray
      generate: false
      material: LEATHER_HELMET
    durability:
      max_custom_durability: 602
    equipment:
      id: ecrubyarmor_lightgray
      legacy_armor_rendering_id: ecrubyarmor_lightgray
      slot: HEAD
      slot_attribute_modifiers:
        armor: 4
        armorToughness: 3
  ecrubylegs_lightgray:
    display_name: Ruby Leggings (lightgray)
    resource:
      model_id: 2370
      model_path: auto_generated/ecrubylegs_lightgray
      generate: false
      material: LEATHER_LEGGINGS
    durability:
      max_custom_durability: 602
    equipment:
      id: ecrubyarmor_lightgray
      legacy_armor_rendering_id: ecrubyarmor_lightgray
      slot: LEGS
      slot_attribute_modifiers:
        armor: 6
        armorToughness: 3
  ecrubyboots_lightgray:
    display_name: Ruby Boots (lightgray)
    resource:
      model_id: 2367
      model_path: auto_generated/ecrubyboots_lightgray
      generate: false
      textures:
      - item/ec_elitearmorsvol6/ecrubyboots_lightgray.png
      material: LEATHER_BOOTS
    durability:
      max_custom_durability: 602
    equipment:
      id: ecrubyarmor_lightgray
      legacy_armor_rendering_id: ecrubyarmor_lightgray
      slot: FEET
      slot_attribute_modifiers:
        armor: 4
        armorToughness: 3
  eclightknightchest_lightgray:
    display_name: Lightknight Chestplate (lightgray)
    resource:
      model_id: 2364
      model_path: auto_generated/eclightknightchest_lightgray
      generate: false
      textures:
      - item/ec_elitearmorsvol6/eclightknightchest_lightgray.png
      material: LEATHER_CHESTPLATE
    durability:
      max_custom_durability: 602
    equipment:
      id: eclightknightarmor_lightgray
      legacy_armor_rendering_id: eclightknightarmor_lightgray
      slot: CHEST
      slot_attribute_modifiers:
        armor: 7
        armorToughness: 3
  eclightknighthelmet_lightgray:
    display_name: Lightknight Helmet (lightgray)
    resource:
      model_id: 2365
      model_path: auto_generated/eclightknighthelmet_lightgray
      generate: false
      textures:
      - item/ec_elitearmorsvol6/eclightknighthelmet_lightgray.png
      material: LEATHER_HELMET
    durability:
      max_custom_durability: 602
    equipment:
      id: eclightknightarmor_lightgray
      legacy_armor_rendering_id: eclightknightarmor_lightgray
      slot: HEAD
      slot_attribute_modifiers:
        armor: 4
        armorToughness: 3
  eclightknightlegs_lightgray:
    display_name: Lightknight Leggings (lightgray)
    resource:
      model_id: 2366
      model_path: auto_generated/eclightknightlegs_lightgray
      generate: false
      textures:
      - item/ec_elitearmorsvol6/eclightknightleggings_lightgray.png
      material: LEATHER_LEGGINGS
    durability:
      max_custom_durability: 602
    equipment:
      id: eclightknightarmor_lightgray
      legacy_armor_rendering_id: eclightknightarmor_lightgray
      slot: LEGS
      slot_attribute_modifiers:
        armor: 6
        armorToughness: 3
  eclightknightboots_lightgray:
    display_name: Lightknight Boots (lightgray)
    resource:
      model_id: 2363
      model_path: auto_generated/eclightknightboots_lightgray
      generate: false
      textures:
      - item/ec_elitearmorsvol6/eclightknightboots_lightgray.png
      material: LEATHER_BOOTS
    durability:
      max_custom_durability: 602
    equipment:
      id: eclightknightarmor_lightgray
      legacy_armor_rendering_id: eclightknightarmor_lightgray
      slot: FEET
      slot_attribute_modifiers:
        armor: 4
        armorToughness: 3
  ecbluemechchest_lightgray:
    display_name: Bluemech Chestplate (lightgray)
    resource:
      model_id: 2356
      model_path: auto_generated/ecbluemechchest_lightgray
      generate: false
      textures:
      - item/ec_elitearmorsvol6/ecbluemechchest_lightgray.png
      material: LEATHER_CHESTPLATE
    durability:
      max_custom_durability: 602
    equipment:
      id: ecbluemecharmor_lightgray
      legacy_armor_rendering_id: ecbluemecharmor_lightgray
      slot: CHEST
      slot_attribute_modifiers:
        armor: 7
        armorToughness: 3
  ecbluemechhelmet_lightgray:
    display_name: Bluemech Helmet (lightgray)
    resource:
      model_id: 2357
      model_path: auto_generated/ecbluemechhelmet_lightgray
      generate: false
      textures:
      - item/ec_elitearmorsvol6/ecbluemechhelmet_lightgray.png
      material: LEATHER_HELMET
    durability:
      max_custom_durability: 602
    equipment:
      id: ecbluemecharmor_lightgray
      legacy_armor_rendering_id: ecbluemecharmor_lightgray
      slot: HEAD
      slot_attribute_modifiers:
        armor: 4
        armorToughness: 3
  ecbluemechlegs_lightgray:
    display_name: Bluemech Leggings (lightgray)
    resource:
      model_id: 2358
      model_path: auto_generated/ecbluemechlegs_lightgray
      generate: false
      textures:
      - item/ec_elitearmorsvol6/ecbluemechleggings_lightgray.png
      material: LEATHER_LEGGINGS
    durability:
      max_custom_durability: 602
    equipment:
      id: ecbluemecharmor_lightgray
      legacy_armor_rendering_id: ecbluemecharmor_lightgray
      slot: LEGS
      slot_attribute_modifiers:
        armor: 6
        armorToughness: 3
  ecbluemechboots_lightgray:
    display_name: Bluemech Boots (lightgray)
    resource:
      model_id: 2355
      model_path: auto_generated/ecbluemechboots_lightgray
      generate: false
      textures:
      - item/ec_elitearmorsvol6/ecbluemechboots_lightgray.png
      material: LEATHER_BOOTS
    durability:
      max_custom_durability: 602
    equipment:
      id: ecbluemecharmor_lightgray
      legacy_armor_rendering_id: ecbluemecharmor_lightgray
      slot: FEET
      slot_attribute_modifiers:
        armor: 4
        armorToughness: 3
  eclavabeastchest_lightgray:
    display_name: Lavabeast Chestplate (lightgray)
    resource:
      model_id: 2360
      model_path: auto_generated/eclavabeastchest_lightgray
      generate: false
      textures:
      - item/ec_elitearmorsvol6/eclavabeastchest_lightgray.png
      material: LEATHER_CHESTPLATE
    durability:
      max_custom_durability: 602
    equipment:
      id: eclavabeastarmor_lightgray
      legacy_armor_rendering_id: eclavabeastarmor_lightgray
      slot: CHEST
      slot_attribute_modifiers:
        armor: 7
        armorToughness: 3
  eclavabeasthelmet_lightgray:
    display_name: Lavabeast Helmet (lightgray)
    resource:
      model_id: 2361
      model_path: auto_generated/eclavabeasthelmet_lightgray
      generate: false
      textures:
      - item/ec_elitearmorsvol6/eclavabeasthelmet_lightgray.png
      material: LEATHER_HELMET
    durability:
      max_custom_durability: 602
    equipment:
      id: eclavabeastarmor_lightgray
      legacy_armor_rendering_id: eclavabeastarmor_lightgray
      slot: HEAD
      slot_attribute_modifiers:
        armor: 4
        armorToughness: 3
  eclavabeastlegs_lightgray:
    display_name: Lavabeast Leggings (lightgray)
    resource:
      model_id: 2362
      model_path: auto_generated/eclavabeastlegs_lightgray
      generate: false
      textures:
      - item/ec_elitearmorsvol6/eclavabeastleggings_lightgray.png
      material: LEATHER_LEGGINGS
    durability:
      max_custom_durability: 602
    equipment:
      id: eclavabeastarmor_lightgray
      legacy_armor_rendering_id: eclavabeastarmor_lightgray
      slot: LEGS
      slot_attribute_modifiers:
        armor: 6
        armorToughness: 3
  eclavabeastboots_lightgray:
    display_name: Lavabeast Boots (lightgray)
    resource:
      model_id: 2359
      model_path: auto_generated/eclavabeastboots_lightgray
      generate: false
      textures:
      - item/ec_elitearmorsvol6/eclavabeastboots_lightgray.png
      material: LEATHER_BOOTS
    durability:
      max_custom_durability: 602
    equipment:
      id: eclavabeastarmor_lightgray
      legacy_armor_rendering_id: eclavabeastarmor_lightgray
      slot: FEET
      slot_attribute_modifiers:
        armor: 4
        armorToughness: 3
