info:
  namespace: ec_elitearmors
armors_rendering:
  ecrubyarmor_darkgreen:
    color: '#5cec36'
    layer_1: armor/ec_elitearmorsvol6/ecrubyarmor_darkgreen
    layer_2: armor/ec_elitearmorsvol6/ecrubyarmor_darkgreen_2
    emissive_1: armor/ec_elitearmorsvol6/ecrubyarmore_1
    emissive_2: armor/ec_elitearmorsvol6/ecrubyarmore_2
    use_color: false
  eclightknightarmor_darkgreen:
    color: '#66f6b8'
    layer_1: armor/ec_elitearmorsvol6/eclightknightarmor_darkgreen
    layer_2: armor/ec_elitearmorsvol6/eclightknightarmor_darkgreen_2
    emissive_1: armor/ec_elitearmorsvol6/eclightknightarmore_1
    emissive_2: armor/ec_elitearmorsvol6/eclightknightarmore_2
    use_color: false
  ecbluemecharmor_darkgreen:
    color: '#87dfc1'
    layer_1: armor/ec_elitearmorsvol6/ecbluemecharmor_darkgreen
    layer_2: armor/ec_elitearmorsvol6/ecbluemecharmor_darkgreen_2
    emissive_1: armor/ec_elitearmorsvol6/ecbluemecharmore_1
    emissive_2: armor/ec_elitearmorsvol6/ecbluemecharmore_2
    use_color: false
  eclavabeastarmor_darkgreen:
    color: '#28a7f9'
    layer_1: armor/ec_elitearmorsvol6/eclavabeastarmor_darkgreen
    layer_2: armor/ec_elitearmorsvol6/eclavabeastarmor_darkgreen_2
    emissive_1: armor/ec_elitearmorsvol6/eclavabeastarmore_1
    emissive_2: armor/ec_elitearmorsvol6/eclavabeastarmore_2
    use_color: false
equipments:
  ecrubyarmor_darkgreen:
    layer_1: armor/ec_elitearmorsvol6/ecrubyarmor_darkgreen
    layer_2: armor/ec_elitearmorsvol6/ecrubyarmor_darkgreen_2
  eclightknightarmor_darkgreen:
    layer_1: armor/ec_elitearmorsvol6/eclightknightarmor_darkgreen
    layer_2: armor/ec_elitearmorsvol6/eclightknightarmor_darkgreen_2
  ecbluemecharmor_darkgreen:
    layer_1: armor/ec_elitearmorsvol6/ecbluemecharmor_darkgreen
    layer_2: armor/ec_elitearmorsvol6/ecbluemecharmor_darkgreen_2
  eclavabeastarmor_darkgreen:
    layer_1: armor/ec_elitearmorsvol6/eclavabeastarmor_darkgreen
    layer_2: armor/ec_elitearmorsvol6/eclavabeastarmor_darkgreen_2
items:
  ecrubychest_darkgreen:
    display_name: Ruby Chestplate (darkgreen)
    resource:
      model_id: 2624
      model_path: auto_generated/ecrubychest_darkgreen
      generate: false
      textures:
      - item/ec_elitearmorsvol6/ecrubychest_darkgreen.png
      material: LEATHER_CHESTPLATE
    durability:
      max_custom_durability: 602
    equipment:
      id: ecrubyarmor_darkgreen
      legacy_armor_rendering_id: ecrubyarmor_darkgreen
      slot: CHEST
      slot_attribute_modifiers:
        armor: 7
        armorToughness: 3
  ecrubyhelmet_darkgreen:
    display_name: Ruby Helmet (darkgreen)
    resource:
      model_id: 2625
      model_path: auto_generated/ecrubyhelmet_darkgreen
      generate: false
      material: LEATHER_HELMET
    durability:
      max_custom_durability: 602
    equipment:
      id: ecrubyarmor_darkgreen
      legacy_armor_rendering_id: ecrubyarmor_darkgreen
      slot: HEAD
      slot_attribute_modifiers:
        armor: 4
        armorToughness: 3
  ecrubylegs_darkgreen:
    display_name: Ruby Leggings (darkgreen)
    resource:
      model_id: 2626
      model_path: auto_generated/ecrubylegs_darkgreen
      generate: false
      material: LEATHER_LEGGINGS
    durability:
      max_custom_durability: 602
    equipment:
      id: ecrubyarmor_darkgreen
      legacy_armor_rendering_id: ecrubyarmor_darkgreen
      slot: LEGS
      slot_attribute_modifiers:
        armor: 6
        armorToughness: 3
  ecrubyboots_darkgreen:
    display_name: Ruby Boots (darkgreen)
    resource:
      model_id: 2623
      model_path: auto_generated/ecrubyboots_darkgreen
      generate: false
      textures:
      - item/ec_elitearmorsvol6/ecrubyboots_darkgreen.png
      material: LEATHER_BOOTS
    durability:
      max_custom_durability: 602
    equipment:
      id: ecrubyarmor_darkgreen
      legacy_armor_rendering_id: ecrubyarmor_darkgreen
      slot: FEET
      slot_attribute_modifiers:
        armor: 4
        armorToughness: 3
  eclightknightchest_darkgreen:
    display_name: Lightknight Chestplate (darkgreen)
    resource:
      model_id: 2620
      model_path: auto_generated/eclightknightchest_darkgreen
      generate: false
      textures:
      - item/ec_elitearmorsvol6/eclightknightchest_darkgreen.png
      material: LEATHER_CHESTPLATE
    durability:
      max_custom_durability: 602
    equipment:
      id: eclightknightarmor_darkgreen
      legacy_armor_rendering_id: eclightknightarmor_darkgreen
      slot: CHEST
      slot_attribute_modifiers:
        armor: 7
        armorToughness: 3
  eclightknighthelmet_darkgreen:
    display_name: Lightknight Helmet (darkgreen)
    resource:
      model_id: 2621
      model_path: auto_generated/eclightknighthelmet_darkgreen
      generate: false
      textures:
      - item/ec_elitearmorsvol6/eclightknighthelmet_darkgreen.png
      material: LEATHER_HELMET
    durability:
      max_custom_durability: 602
    equipment:
      id: eclightknightarmor_darkgreen
      legacy_armor_rendering_id: eclightknightarmor_darkgreen
      slot: HEAD
      slot_attribute_modifiers:
        armor: 4
        armorToughness: 3
  eclightknightlegs_darkgreen:
    display_name: Lightknight Leggings (darkgreen)
    resource:
      model_id: 2622
      model_path: auto_generated/eclightknightlegs_darkgreen
      generate: false
      textures:
      - item/ec_elitearmorsvol6/eclightknightleggings_darkgreen.png
      material: LEATHER_LEGGINGS
    durability:
      max_custom_durability: 602
    equipment:
      id: eclightknightarmor_darkgreen
      legacy_armor_rendering_id: eclightknightarmor_darkgreen
      slot: LEGS
      slot_attribute_modifiers:
        armor: 6
        armorToughness: 3
  eclightknightboots_darkgreen:
    display_name: Lightknight Boots (darkgreen)
    resource:
      model_id: 2619
      model_path: auto_generated/eclightknightboots_darkgreen
      generate: false
      textures:
      - item/ec_elitearmorsvol6/eclightknightboots_darkgreen.png
      material: LEATHER_BOOTS
    durability:
      max_custom_durability: 602
    equipment:
      id: eclightknightarmor_darkgreen
      legacy_armor_rendering_id: eclightknightarmor_darkgreen
      slot: FEET
      slot_attribute_modifiers:
        armor: 4
        armorToughness: 3
  ecbluemechchest_darkgreen:
    display_name: Bluemech Chestplate (darkgreen)
    resource:
      model_id: 2612
      model_path: auto_generated/ecbluemechchest_darkgreen
      generate: false
      textures:
      - item/ec_elitearmorsvol6/ecbluemechchest_darkgreen.png
      material: LEATHER_CHESTPLATE
    durability:
      max_custom_durability: 602
    equipment:
      id: ecbluemecharmor_darkgreen
      legacy_armor_rendering_id: ecbluemecharmor_darkgreen
      slot: CHEST
      slot_attribute_modifiers:
        armor: 7
        armorToughness: 3
  ecbluemechhelmet_darkgreen:
    display_name: Bluemech Helmet (darkgreen)
    resource:
      model_id: 2613
      model_path: auto_generated/ecbluemechhelmet_darkgreen
      generate: false
      textures:
      - item/ec_elitearmorsvol6/ecbluemechhelmet_darkgreen.png
      material: LEATHER_HELMET
    durability:
      max_custom_durability: 602
    equipment:
      id: ecbluemecharmor_darkgreen
      legacy_armor_rendering_id: ecbluemecharmor_darkgreen
      slot: HEAD
      slot_attribute_modifiers:
        armor: 4
        armorToughness: 3
  ecbluemechlegs_darkgreen:
    display_name: Bluemech Leggings (darkgreen)
    resource:
      model_id: 2614
      model_path: auto_generated/ecbluemechlegs_darkgreen
      generate: false
      textures:
      - item/ec_elitearmorsvol6/ecbluemechleggings_darkgreen.png
      material: LEATHER_LEGGINGS
    durability:
      max_custom_durability: 602
    equipment:
      id: ecbluemecharmor_darkgreen
      legacy_armor_rendering_id: ecbluemecharmor_darkgreen
      slot: LEGS
      slot_attribute_modifiers:
        armor: 6
        armorToughness: 3
  ecbluemechboots_darkgreen:
    display_name: Bluemech Boots (darkgreen)
    resource:
      model_id: 2611
      model_path: auto_generated/ecbluemechboots_darkgreen
      generate: false
      textures:
      - item/ec_elitearmorsvol6/ecbluemechboots_darkgreen.png
      material: LEATHER_BOOTS
    durability:
      max_custom_durability: 602
    equipment:
      id: ecbluemecharmor_darkgreen
      legacy_armor_rendering_id: ecbluemecharmor_darkgreen
      slot: FEET
      slot_attribute_modifiers:
        armor: 4
        armorToughness: 3
  eclavabeastchest_darkgreen:
    display_name: Lavabeast Chestplate (darkgreen)
    resource:
      model_id: 2616
      model_path: auto_generated/eclavabeastchest_darkgreen
      generate: false
      textures:
      - item/ec_elitearmorsvol6/eclavabeastchest_darkgreen.png
      material: LEATHER_CHESTPLATE
    durability:
      max_custom_durability: 602
    equipment:
      id: eclavabeastarmor_darkgreen
      legacy_armor_rendering_id: eclavabeastarmor_darkgreen
      slot: CHEST
      slot_attribute_modifiers:
        armor: 7
        armorToughness: 3
  eclavabeasthelmet_darkgreen:
    display_name: Lavabeast Helmet (darkgreen)
    resource:
      model_id: 2617
      model_path: auto_generated/eclavabeasthelmet_darkgreen
      generate: false
      textures:
      - item/ec_elitearmorsvol6/eclavabeasthelmet_darkgreen.png
      material: LEATHER_HELMET
    durability:
      max_custom_durability: 602
    equipment:
      id: eclavabeastarmor_darkgreen
      legacy_armor_rendering_id: eclavabeastarmor_darkgreen
      slot: HEAD
      slot_attribute_modifiers:
        armor: 4
        armorToughness: 3
  eclavabeastlegs_darkgreen:
    display_name: Lavabeast Leggings (darkgreen)
    resource:
      model_id: 2618
      model_path: auto_generated/eclavabeastlegs_darkgreen
      generate: false
      textures:
      - item/ec_elitearmorsvol6/eclavabeastleggings_darkgreen.png
      material: LEATHER_LEGGINGS
    durability:
      max_custom_durability: 602
    equipment:
      id: eclavabeastarmor_darkgreen
      legacy_armor_rendering_id: eclavabeastarmor_darkgreen
      slot: LEGS
      slot_attribute_modifiers:
        armor: 6
        armorToughness: 3
  eclavabeastboots_darkgreen:
    display_name: Lavabeast Boots (darkgreen)
    resource:
      model_id: 2615
      model_path: auto_generated/eclavabeastboots_darkgreen
      generate: false
      textures:
      - item/ec_elitearmorsvol6/eclavabeastboots_darkgreen.png
      material: LEATHER_BOOTS
    durability:
      max_custom_durability: 602
    equipment:
      id: eclavabeastarmor_darkgreen
      legacy_armor_rendering_id: eclavabeastarmor_darkgreen
      slot: FEET
      slot_attribute_modifiers:
        armor: 4
        armorToughness: 3
