info:
  namespace: ec_elitearmors
armors_rendering:
  ecrubyarmor_gray:
    color: '#5cec44'
    layer_1: armor/ec_elitearmorsvol6/ecrubyarmor_gray
    layer_2: armor/ec_elitearmorsvol6/ecrubyarmor_gray_2
    emissive_1: armor/ec_elitearmorsvol6/ecrubyarmore_1
    emissive_2: armor/ec_elitearmorsvol6/ecrubyarmore_2
    use_color: false
  eclightknightarmor_gray:
    color: '#66f6c6'
    layer_1: armor/ec_elitearmorsvol6/eclightknightarmor_gray
    layer_2: armor/ec_elitearmorsvol6/eclightknightarmor_gray_2
    emissive_1: armor/ec_elitearmorsvol6/eclightknightarmore_1
    emissive_2: armor/ec_elitearmorsvol6/eclightknightarmore_2
    use_color: false
  ecbluemecharmor_gray:
    color: '#87dfcf'
    layer_1: armor/ec_elitearmorsvol6/ecbluemecharmor_gray
    layer_2: armor/ec_elitearmorsvol6/ecbluemecharmor_gray_2
    emissive_1: armor/ec_elitearmorsvol6/ecbluemecharmore_1
    emissive_2: armor/ec_elitearmorsvol6/ecbluemecharmore_2
    use_color: false
  eclavabeastarmor_gray:
    color: '#28a807'
    layer_1: armor/ec_elitearmorsvol6/eclavabeastarmor_gray
    layer_2: armor/ec_elitearmorsvol6/eclavabeastarmor_gray_2
    emissive_1: armor/ec_elitearmorsvol6/eclavabeastarmore_1
    emissive_2: armor/ec_elitearmorsvol6/eclavabeastarmore_2
    use_color: false
equipments:
  ecrubyarmor_gray:
    layer_1: armor/ec_elitearmorsvol6/ecrubyarmor_gray
    layer_2: armor/ec_elitearmorsvol6/ecrubyarmor_gray_2
  eclightknightarmor_gray:
    layer_1: armor/ec_elitearmorsvol6/eclightknightarmor_gray
    layer_2: armor/ec_elitearmorsvol6/eclightknightarmor_gray_2
  ecbluemecharmor_gray:
    layer_1: armor/ec_elitearmorsvol6/ecbluemecharmor_gray
    layer_2: armor/ec_elitearmorsvol6/ecbluemecharmor_gray_2
  eclavabeastarmor_gray:
    layer_1: armor/ec_elitearmorsvol6/eclavabeastarmor_gray
    layer_2: armor/ec_elitearmorsvol6/eclavabeastarmor_gray_2
items:
  ecrubychest_gray:
    display_name: Ruby Chestplate (gray)
    resource:
      model_id: 2384
      model_path: auto_generated/ecrubychest_gray
      generate: false
      textures:
      - item/ec_elitearmorsvol6/ecrubychest_gray.png
      material: LEATHER_CHESTPLATE
    durability:
      max_custom_durability: 602
    equipment:
      id: ecrubyarmor_gray
      legacy_armor_rendering_id: ecrubyarmor_gray
      slot: CHEST
      slot_attribute_modifiers:
        armor: 7
        armorToughness: 3
  ecrubyhelmet_gray:
    display_name: Ruby Helmet (gray)
    resource:
      model_id: 2385
      model_path: auto_generated/ecrubyhelmet_gray
      generate: false
      material: LEATHER_HELMET
    durability:
      max_custom_durability: 602
    equipment:
      id: ecrubyarmor_gray
      legacy_armor_rendering_id: ecrubyarmor_gray
      slot: HEAD
      slot_attribute_modifiers:
        armor: 4
        armorToughness: 3
  ecrubylegs_gray:
    display_name: Ruby Leggings (gray)
    resource:
      model_id: 2386
      model_path: auto_generated/ecrubylegs_gray
      generate: false
      material: LEATHER_LEGGINGS
    durability:
      max_custom_durability: 602
    equipment:
      id: ecrubyarmor_gray
      legacy_armor_rendering_id: ecrubyarmor_gray
      slot: LEGS
      slot_attribute_modifiers:
        armor: 6
        armorToughness: 3
  ecrubyboots_gray:
    display_name: Ruby Boots (gray)
    resource:
      model_id: 2383
      model_path: auto_generated/ecrubyboots_gray
      generate: false
      textures:
      - item/ec_elitearmorsvol6/ecrubyboots_gray.png
      material: LEATHER_BOOTS
    durability:
      max_custom_durability: 602
    equipment:
      id: ecrubyarmor_gray
      legacy_armor_rendering_id: ecrubyarmor_gray
      slot: FEET
      slot_attribute_modifiers:
        armor: 4
        armorToughness: 3
  eclightknightchest_gray:
    display_name: Lightknight Chestplate (gray)
    resource:
      model_id: 2380
      model_path: auto_generated/eclightknightchest_gray
      generate: false
      textures:
      - item/ec_elitearmorsvol6/eclightknightchest_gray.png
      material: LEATHER_CHESTPLATE
    durability:
      max_custom_durability: 602
    equipment:
      id: eclightknightarmor_gray
      legacy_armor_rendering_id: eclightknightarmor_gray
      slot: CHEST
      slot_attribute_modifiers:
        armor: 7
        armorToughness: 3
  eclightknighthelmet_gray:
    display_name: Lightknight Helmet (gray)
    resource:
      model_id: 2381
      model_path: auto_generated/eclightknighthelmet_gray
      generate: false
      textures:
      - item/ec_elitearmorsvol6/eclightknighthelmet_gray.png
      material: LEATHER_HELMET
    durability:
      max_custom_durability: 602
    equipment:
      id: eclightknightarmor_gray
      legacy_armor_rendering_id: eclightknightarmor_gray
      slot: HEAD
      slot_attribute_modifiers:
        armor: 4
        armorToughness: 3
  eclightknightlegs_gray:
    display_name: Lightknight Leggings (gray)
    resource:
      model_id: 2382
      model_path: auto_generated/eclightknightlegs_gray
      generate: false
      textures:
      - item/ec_elitearmorsvol6/eclightknightleggings_gray.png
      material: LEATHER_LEGGINGS
    durability:
      max_custom_durability: 602
    equipment:
      id: eclightknightarmor_gray
      legacy_armor_rendering_id: eclightknightarmor_gray
      slot: LEGS
      slot_attribute_modifiers:
        armor: 6
        armorToughness: 3
  eclightknightboots_gray:
    display_name: Lightknight Boots (gray)
    resource:
      model_id: 2379
      model_path: auto_generated/eclightknightboots_gray
      generate: false
      textures:
      - item/ec_elitearmorsvol6/eclightknightboots_gray.png
      material: LEATHER_BOOTS
    durability:
      max_custom_durability: 602
    equipment:
      id: eclightknightarmor_gray
      legacy_armor_rendering_id: eclightknightarmor_gray
      slot: FEET
      slot_attribute_modifiers:
        armor: 4
        armorToughness: 3
  ecbluemechchest_gray:
    display_name: Bluemech Chestplate (gray)
    resource:
      model_id: 2372
      model_path: auto_generated/ecbluemechchest_gray
      generate: false
      textures:
      - item/ec_elitearmorsvol6/ecbluemechchest_gray.png
      material: LEATHER_CHESTPLATE
    durability:
      max_custom_durability: 602
    equipment:
      id: ecbluemecharmor_gray
      legacy_armor_rendering_id: ecbluemecharmor_gray
      slot: CHEST
      slot_attribute_modifiers:
        armor: 7
        armorToughness: 3
  ecbluemechhelmet_gray:
    display_name: Bluemech Helmet (gray)
    resource:
      model_id: 2373
      model_path: auto_generated/ecbluemechhelmet_gray
      generate: false
      textures:
      - item/ec_elitearmorsvol6/ecbluemechhelmet_gray.png
      material: LEATHER_HELMET
    durability:
      max_custom_durability: 602
    equipment:
      id: ecbluemecharmor_gray
      legacy_armor_rendering_id: ecbluemecharmor_gray
      slot: HEAD
      slot_attribute_modifiers:
        armor: 4
        armorToughness: 3
  ecbluemechlegs_gray:
    display_name: Bluemech Leggings (gray)
    resource:
      model_id: 2374
      model_path: auto_generated/ecbluemechlegs_gray
      generate: false
      textures:
      - item/ec_elitearmorsvol6/ecbluemechleggings_gray.png
      material: LEATHER_LEGGINGS
    durability:
      max_custom_durability: 602
    equipment:
      id: ecbluemecharmor_gray
      legacy_armor_rendering_id: ecbluemecharmor_gray
      slot: LEGS
      slot_attribute_modifiers:
        armor: 6
        armorToughness: 3
  ecbluemechboots_gray:
    display_name: Bluemech Boots (gray)
    resource:
      model_id: 2371
      model_path: auto_generated/ecbluemechboots_gray
      generate: false
      textures:
      - item/ec_elitearmorsvol6/ecbluemechboots_gray.png
      material: LEATHER_BOOTS
    durability:
      max_custom_durability: 602
    equipment:
      id: ecbluemecharmor_gray
      legacy_armor_rendering_id: ecbluemecharmor_gray
      slot: FEET
      slot_attribute_modifiers:
        armor: 4
        armorToughness: 3
  eclavabeastchest_gray:
    display_name: Lavabeast Chestplate (gray)
    resource:
      model_id: 2376
      model_path: auto_generated/eclavabeastchest_gray
      generate: false
      textures:
      - item/ec_elitearmorsvol6/eclavabeastchest_gray.png
      material: LEATHER_CHESTPLATE
    durability:
      max_custom_durability: 602
    equipment:
      id: eclavabeastarmor_gray
      legacy_armor_rendering_id: eclavabeastarmor_gray
      slot: CHEST
      slot_attribute_modifiers:
        armor: 7
        armorToughness: 3
  eclavabeasthelmet_gray:
    display_name: Lavabeast Helmet (gray)
    resource:
      model_id: 2377
      model_path: auto_generated/eclavabeasthelmet_gray
      generate: false
      textures:
      - item/ec_elitearmorsvol6/eclavabeasthelmet_gray.png
      material: LEATHER_HELMET
    durability:
      max_custom_durability: 602
    equipment:
      id: eclavabeastarmor_gray
      legacy_armor_rendering_id: eclavabeastarmor_gray
      slot: HEAD
      slot_attribute_modifiers:
        armor: 4
        armorToughness: 3
  eclavabeastlegs_gray:
    display_name: Lavabeast Leggings (gray)
    resource:
      model_id: 2378
      model_path: auto_generated/eclavabeastlegs_gray
      generate: false
      textures:
      - item/ec_elitearmorsvol6/eclavabeastleggings_gray.png
      material: LEATHER_LEGGINGS
    durability:
      max_custom_durability: 602
    equipment:
      id: eclavabeastarmor_gray
      legacy_armor_rendering_id: eclavabeastarmor_gray
      slot: LEGS
      slot_attribute_modifiers:
        armor: 6
        armorToughness: 3
  eclavabeastboots_gray:
    display_name: Lavabeast Boots (gray)
    resource:
      model_id: 2375
      model_path: auto_generated/eclavabeastboots_gray
      generate: false
      textures:
      - item/ec_elitearmorsvol6/eclavabeastboots_gray.png
      material: LEATHER_BOOTS
    durability:
      max_custom_durability: 602
    equipment:
      id: eclavabeastarmor_gray
      legacy_armor_rendering_id: eclavabeastarmor_gray
      slot: FEET
      slot_attribute_modifiers:
        armor: 4
        armorToughness: 3
