info:
  namespace: ec_elitearmors
armors_rendering:
  ecrubyarmor_darkpurple:
    color: '#5cec33'
    layer_1: armor/ec_elitearmorsvol6/ecrubyarmor_darkpurple
    layer_2: armor/ec_elitearmorsvol6/ecrubyarmor_darkpurple_2
    emissive_1: armor/ec_elitearmorsvol6/ecrubyarmore_1
    emissive_2: armor/ec_elitearmorsvol6/ecrubyarmore_2
    use_color: false
  eclightknightarmor_darkpurple:
    color: '#66f6b5'
    layer_1: armor/ec_elitearmorsvol6/eclightknightarmor_darkpurple
    layer_2: armor/ec_elitearmorsvol6/eclightknightarmor_darkpurple_2
    emissive_1: armor/ec_elitearmorsvol6/eclightknightarmore_1
    emissive_2: armor/ec_elitearmorsvol6/eclightknightarmore_2
    use_color: false
  ecbluemecharmor_darkpurple:
    color: '#87dfbe'
    layer_1: armor/ec_elitearmorsvol6/ecbluemecharmor_darkpurple
    layer_2: armor/ec_elitearmorsvol6/ecbluemecharmor_darkpurple_2
    emissive_1: armor/ec_elitearmorsvol6/ecbluemecharmore_1
    emissive_2: armor/ec_elitearmorsvol6/ecbluemecharmore_2
    use_color: false
  eclavabeastarmor_darkpurple:
    color: '#28a7f6'
    layer_1: armor/ec_elitearmorsvol6/eclavabeastarmor_darkpurple
    layer_2: armor/ec_elitearmorsvol6/eclavabeastarmor_darkpurple_2
    emissive_1: armor/ec_elitearmorsvol6/eclavabeastarmore_1
    emissive_2: armor/ec_elitearmorsvol6/eclavabeastarmore_2
    use_color: false
equipments:
  ecrubyarmor_darkpurple:
    layer_1: armor/ec_elitearmorsvol6/ecrubyarmor_darkpurple
    layer_2: armor/ec_elitearmorsvol6/ecrubyarmor_darkpurple_2
  eclightknightarmor_darkpurple:
    layer_1: armor/ec_elitearmorsvol6/eclightknightarmor_darkpurple
    layer_2: armor/ec_elitearmorsvol6/eclightknightarmor_darkpurple_2
  ecbluemecharmor_darkpurple:
    layer_1: armor/ec_elitearmorsvol6/ecbluemecharmor_darkpurple
    layer_2: armor/ec_elitearmorsvol6/ecbluemecharmor_darkpurple_2
  eclavabeastarmor_darkpurple:
    layer_1: armor/ec_elitearmorsvol6/eclavabeastarmor_darkpurple
    layer_2: armor/ec_elitearmorsvol6/eclavabeastarmor_darkpurple_2
items:
  ecrubychest_darkpurple:
    display_name: Ruby Chestplate (darkpurple)
    resource:
      model_id: 2752
      model_path: auto_generated/ecrubychest_darkpurple
      generate: false
      textures:
      - item/ec_elitearmorsvol6/ecrubychest_darkpurple.png
      material: LEATHER_CHESTPLATE
    durability:
      max_custom_durability: 602
    equipment:
      id: ecrubyarmor_darkpurple
      legacy_armor_rendering_id: ecrubyarmor_darkpurple
      slot: CHEST
      slot_attribute_modifiers:
        armor: 7
        armorToughness: 3
  ecrubyhelmet_darkpurple:
    display_name: Ruby Helmet (darkpurple)
    resource:
      model_id: 2753
      model_path: auto_generated/ecrubyhelmet_darkpurple
      generate: false
      material: LEATHER_HELMET
    durability:
      max_custom_durability: 602
    equipment:
      id: ecrubyarmor_darkpurple
      legacy_armor_rendering_id: ecrubyarmor_darkpurple
      slot: HEAD
      slot_attribute_modifiers:
        armor: 4
        armorToughness: 3
  ecrubylegs_darkpurple:
    display_name: Ruby Leggings (darkpurple)
    resource:
      model_id: 2754
      model_path: auto_generated/ecrubylegs_darkpurple
      generate: false
      material: LEATHER_LEGGINGS
    durability:
      max_custom_durability: 602
    equipment:
      id: ecrubyarmor_darkpurple
      legacy_armor_rendering_id: ecrubyarmor_darkpurple
      slot: LEGS
      slot_attribute_modifiers:
        armor: 6
        armorToughness: 3
  ecrubyboots_darkpurple:
    display_name: Ruby Boots (darkpurple)
    resource:
      model_id: 2751
      model_path: auto_generated/ecrubyboots_darkpurple
      generate: false
      textures:
      - item/ec_elitearmorsvol6/ecrubyboots_darkpurple.png
      material: LEATHER_BOOTS
    durability:
      max_custom_durability: 602
    equipment:
      id: ecrubyarmor_darkpurple
      legacy_armor_rendering_id: ecrubyarmor_darkpurple
      slot: FEET
      slot_attribute_modifiers:
        armor: 4
        armorToughness: 3
  eclightknightchest_darkpurple:
    display_name: Lightknight Chestplate (darkpurple)
    resource:
      model_id: 2748
      model_path: auto_generated/eclightknightchest_darkpurple
      generate: false
      textures:
      - item/ec_elitearmorsvol6/eclightknightchest_darkpurple.png
      material: LEATHER_CHESTPLATE
    durability:
      max_custom_durability: 602
    equipment:
      id: eclightknightarmor_darkpurple
      legacy_armor_rendering_id: eclightknightarmor_darkpurple
      slot: CHEST
      slot_attribute_modifiers:
        armor: 7
        armorToughness: 3
  eclightknighthelmet_darkpurple:
    display_name: Lightknight Helmet (darkpurple)
    resource:
      model_id: 2749
      model_path: auto_generated/eclightknighthelmet_darkpurple
      generate: false
      textures:
      - item/ec_elitearmorsvol6/eclightknighthelmet_darkpurple.png
      material: LEATHER_HELMET
    durability:
      max_custom_durability: 602
    equipment:
      id: eclightknightarmor_darkpurple
      legacy_armor_rendering_id: eclightknightarmor_darkpurple
      slot: HEAD
      slot_attribute_modifiers:
        armor: 4
        armorToughness: 3
  eclightknightlegs_darkpurple:
    display_name: Lightknight Leggings (darkpurple)
    resource:
      model_id: 2750
      model_path: auto_generated/eclightknightlegs_darkpurple
      generate: false
      textures:
      - item/ec_elitearmorsvol6/eclightknightleggings_darkpurple.png
      material: LEATHER_LEGGINGS
    durability:
      max_custom_durability: 602
    equipment:
      id: eclightknightarmor_darkpurple
      legacy_armor_rendering_id: eclightknightarmor_darkpurple
      slot: LEGS
      slot_attribute_modifiers:
        armor: 6
        armorToughness: 3
  eclightknightboots_darkpurple:
    display_name: Lightknight Boots (darkpurple)
    resource:
      model_id: 2747
      model_path: auto_generated/eclightknightboots_darkpurple
      generate: false
      textures:
      - item/ec_elitearmorsvol6/eclightknightboots_darkpurple.png
      material: LEATHER_BOOTS
    durability:
      max_custom_durability: 602
    equipment:
      id: eclightknightarmor_darkpurple
      legacy_armor_rendering_id: eclightknightarmor_darkpurple
      slot: FEET
      slot_attribute_modifiers:
        armor: 4
        armorToughness: 3
  ecbluemechchest_darkpurple:
    display_name: Bluemech Chestplate (darkpurple)
    resource:
      model_id: 2740
      model_path: auto_generated/ecbluemechchest_darkpurple
      generate: false
      textures:
      - item/ec_elitearmorsvol6/ecbluemechchest_darkpurple.png
      material: LEATHER_CHESTPLATE
    durability:
      max_custom_durability: 602
    equipment:
      id: ecbluemecharmor_darkpurple
      legacy_armor_rendering_id: ecbluemecharmor_darkpurple
      slot: CHEST
      slot_attribute_modifiers:
        armor: 7
        armorToughness: 3
  ecbluemechhelmet_darkpurple:
    display_name: Bluemech Helmet (darkpurple)
    resource:
      model_id: 2741
      model_path: auto_generated/ecbluemechhelmet_darkpurple
      generate: false
      textures:
      - item/ec_elitearmorsvol6/ecbluemechhelmet_darkpurple.png
      material: LEATHER_HELMET
    durability:
      max_custom_durability: 602
    equipment:
      id: ecbluemecharmor_darkpurple
      legacy_armor_rendering_id: ecbluemecharmor_darkpurple
      slot: HEAD
      slot_attribute_modifiers:
        armor: 4
        armorToughness: 3
  ecbluemechlegs_darkpurple:
    display_name: Bluemech Leggings (darkpurple)
    resource:
      model_id: 2742
      model_path: auto_generated/ecbluemechlegs_darkpurple
      generate: false
      textures:
      - item/ec_elitearmorsvol6/ecbluemechleggings_darkpurple.png
      material: LEATHER_LEGGINGS
    durability:
      max_custom_durability: 602
    equipment:
      id: ecbluemecharmor_darkpurple
      legacy_armor_rendering_id: ecbluemecharmor_darkpurple
      slot: LEGS
      slot_attribute_modifiers:
        armor: 6
        armorToughness: 3
  ecbluemechboots_darkpurple:
    display_name: Bluemech Boots (darkpurple)
    resource:
      model_id: 2739
      model_path: auto_generated/ecbluemechboots_darkpurple
      generate: false
      textures:
      - item/ec_elitearmorsvol6/ecbluemechboots_darkpurple.png
      material: LEATHER_BOOTS
    durability:
      max_custom_durability: 602
    equipment:
      id: ecbluemecharmor_darkpurple
      legacy_armor_rendering_id: ecbluemecharmor_darkpurple
      slot: FEET
      slot_attribute_modifiers:
        armor: 4
        armorToughness: 3
  eclavabeastchest_darkpurple:
    display_name: Lavabeast Chestplate (darkpurple)
    resource:
      model_id: 2744
      model_path: auto_generated/eclavabeastchest_darkpurple
      generate: false
      textures:
      - item/ec_elitearmorsvol6/eclavabeastchest_darkpurple.png
      material: LEATHER_CHESTPLATE
    durability:
      max_custom_durability: 602
    equipment:
      id: eclavabeastarmor_darkpurple
      legacy_armor_rendering_id: eclavabeastarmor_darkpurple
      slot: CHEST
      slot_attribute_modifiers:
        armor: 7
        armorToughness: 3
  eclavabeasthelmet_darkpurple:
    display_name: Lavabeast Helmet (darkpurple)
    resource:
      model_id: 2745
      model_path: auto_generated/eclavabeasthelmet_darkpurple
      generate: false
      textures:
      - item/ec_elitearmorsvol6/eclavabeasthelmet_darkpurple.png
      material: LEATHER_HELMET
    durability:
      max_custom_durability: 602
    equipment:
      id: eclavabeastarmor_darkpurple
      legacy_armor_rendering_id: eclavabeastarmor_darkpurple
      slot: HEAD
      slot_attribute_modifiers:
        armor: 4
        armorToughness: 3
  eclavabeastlegs_darkpurple:
    display_name: Lavabeast Leggings (darkpurple)
    resource:
      model_id: 2746
      model_path: auto_generated/eclavabeastlegs_darkpurple
      generate: false
      textures:
      - item/ec_elitearmorsvol6/eclavabeastleggings_darkpurple.png
      material: LEATHER_LEGGINGS
    durability:
      max_custom_durability: 602
    equipment:
      id: eclavabeastarmor_darkpurple
      legacy_armor_rendering_id: eclavabeastarmor_darkpurple
      slot: LEGS
      slot_attribute_modifiers:
        armor: 6
        armorToughness: 3
  eclavabeastboots_darkpurple:
    display_name: Lavabeast Boots (darkpurple)
    resource:
      model_id: 2743
      model_path: auto_generated/eclavabeastboots_darkpurple
      generate: false
      textures:
      - item/ec_elitearmorsvol6/eclavabeastboots_darkpurple.png
      material: LEATHER_BOOTS
    durability:
      max_custom_durability: 602
    equipment:
      id: eclavabeastarmor_darkpurple
      legacy_armor_rendering_id: eclavabeastarmor_darkpurple
      slot: FEET
      slot_attribute_modifiers:
        armor: 4
        armorToughness: 3
