info:
  namespace: ec_elitearmors
armors_rendering:
  ecrubyarmor_purple:
    color: '#5cec3e'
    layer_1: armor/ec_elitearmorsvol6/ecrubyarmor_purple
    layer_2: armor/ec_elitearmorsvol6/ecrubyarmor_purple_2
    emissive_1: armor/ec_elitearmorsvol6/ecrubyarmore_1
    emissive_2: armor/ec_elitearmorsvol6/ecrubyarmore_2
    use_color: false
  eclightknightarmor_purple:
    color: '#66f6c0'
    layer_1: armor/ec_elitearmorsvol6/eclightknightarmor_purple
    layer_2: armor/ec_elitearmorsvol6/eclightknightarmor_purple_2
    emissive_1: armor/ec_elitearmorsvol6/eclightknightarmore_1
    emissive_2: armor/ec_elitearmorsvol6/eclightknightarmore_2
    use_color: false
  ecbluemecharmor_purple:
    color: '#87dfc9'
    layer_1: armor/ec_elitearmorsvol6/ecbluemecharmor_purple
    layer_2: armor/ec_elitearmorsvol6/ecbluemecharmor_purple_2
    emissive_1: armor/ec_elitearmorsvol6/ecbluemecharmore_1
    emissive_2: armor/ec_elitearmorsvol6/ecbluemecharmore_2
    use_color: false
  eclavabeastarmor_purple:
    color: '#28a801'
    layer_1: armor/ec_elitearmorsvol6/eclavabeastarmor_purple
    layer_2: armor/ec_elitearmorsvol6/eclavabeastarmor_purple_2
    emissive_1: armor/ec_elitearmorsvol6/eclavabeastarmore_1
    emissive_2: armor/ec_elitearmorsvol6/eclavabeastarmore_2
    use_color: false
equipments:
  ecrubyarmor_purple:
    layer_1: armor/ec_elitearmorsvol6/ecrubyarmor_purple
    layer_2: armor/ec_elitearmorsvol6/ecrubyarmor_purple_2
  eclightknightarmor_purple:
    layer_1: armor/ec_elitearmorsvol6/eclightknightarmor_purple
    layer_2: armor/ec_elitearmorsvol6/eclightknightarmor_purple_2
  ecbluemecharmor_purple:
    layer_1: armor/ec_elitearmorsvol6/ecbluemecharmor_purple
    layer_2: armor/ec_elitearmorsvol6/ecbluemecharmor_purple_2
  eclavabeastarmor_purple:
    layer_1: armor/ec_elitearmorsvol6/eclavabeastarmor_purple
    layer_2: armor/ec_elitearmorsvol6/eclavabeastarmor_purple_2
items:
  ecrubychest_purple:
    display_name: Ruby Chestplate (purple)
    resource:
      model_id: 2736
      model_path: auto_generated/ecrubychest_purple
      generate: false
      textures:
      - item/ec_elitearmorsvol6/ecrubychest_purple.png
      material: LEATHER_CHESTPLATE
    durability:
      max_custom_durability: 602
    equipment:
      id: ecrubyarmor_purple
      legacy_armor_rendering_id: ecrubyarmor_purple
      slot: CHEST
      slot_attribute_modifiers:
        armor: 7
        armorToughness: 3
  ecrubyhelmet_purple:
    display_name: Ruby Helmet (purple)
    resource:
      model_id: 2737
      model_path: auto_generated/ecrubyhelmet_purple
      generate: false
      material: LEATHER_HELMET
    durability:
      max_custom_durability: 602
    equipment:
      id: ecrubyarmor_purple
      legacy_armor_rendering_id: ecrubyarmor_purple
      slot: HEAD
      slot_attribute_modifiers:
        armor: 4
        armorToughness: 3
  ecrubylegs_purple:
    display_name: Ruby Leggings (purple)
    resource:
      model_id: 2738
      model_path: auto_generated/ecrubylegs_purple
      generate: false
      material: LEATHER_LEGGINGS
    durability:
      max_custom_durability: 602
    equipment:
      id: ecrubyarmor_purple
      legacy_armor_rendering_id: ecrubyarmor_purple
      slot: LEGS
      slot_attribute_modifiers:
        armor: 6
        armorToughness: 3
  ecrubyboots_purple:
    display_name: Ruby Boots (purple)
    resource:
      model_id: 2735
      model_path: auto_generated/ecrubyboots_purple
      generate: false
      textures:
      - item/ec_elitearmorsvol6/ecrubyboots_purple.png
      material: LEATHER_BOOTS
    durability:
      max_custom_durability: 602
    equipment:
      id: ecrubyarmor_purple
      legacy_armor_rendering_id: ecrubyarmor_purple
      slot: FEET
      slot_attribute_modifiers:
        armor: 4
        armorToughness: 3
  eclightknightchest_purple:
    display_name: Lightknight Chestplate (purple)
    resource:
      model_id: 2732
      model_path: auto_generated/eclightknightchest_purple
      generate: false
      textures:
      - item/ec_elitearmorsvol6/eclightknightchest_purple.png
      material: LEATHER_CHESTPLATE
    durability:
      max_custom_durability: 602
    equipment:
      id: eclightknightarmor_purple
      legacy_armor_rendering_id: eclightknightarmor_purple
      slot: CHEST
      slot_attribute_modifiers:
        armor: 7
        armorToughness: 3
  eclightknighthelmet_purple:
    display_name: Lightknight Helmet (purple)
    resource:
      model_id: 2733
      model_path: auto_generated/eclightknighthelmet_purple
      generate: false
      textures:
      - item/ec_elitearmorsvol6/eclightknighthelmet_purple.png
      material: LEATHER_HELMET
    durability:
      max_custom_durability: 602
    equipment:
      id: eclightknightarmor_purple
      legacy_armor_rendering_id: eclightknightarmor_purple
      slot: HEAD
      slot_attribute_modifiers:
        armor: 4
        armorToughness: 3
  eclightknightlegs_purple:
    display_name: Lightknight Leggings (purple)
    resource:
      model_id: 2734
      model_path: auto_generated/eclightknightlegs_purple
      generate: false
      textures:
      - item/ec_elitearmorsvol6/eclightknightleggings_purple.png
      material: LEATHER_LEGGINGS
    durability:
      max_custom_durability: 602
    equipment:
      id: eclightknightarmor_purple
      legacy_armor_rendering_id: eclightknightarmor_purple
      slot: LEGS
      slot_attribute_modifiers:
        armor: 6
        armorToughness: 3
  eclightknightboots_purple:
    display_name: Lightknight Boots (purple)
    resource:
      model_id: 2731
      model_path: auto_generated/eclightknightboots_purple
      generate: false
      textures:
      - item/ec_elitearmorsvol6/eclightknightboots_purple.png
      material: LEATHER_BOOTS
    durability:
      max_custom_durability: 602
    equipment:
      id: eclightknightarmor_purple
      legacy_armor_rendering_id: eclightknightarmor_purple
      slot: FEET
      slot_attribute_modifiers:
        armor: 4
        armorToughness: 3
  ecbluemechchest_purple:
    display_name: Bluemech Chestplate (purple)
    resource:
      model_id: 2724
      model_path: auto_generated/ecbluemechchest_purple
      generate: false
      textures:
      - item/ec_elitearmorsvol6/ecbluemechchest_purple.png
      material: LEATHER_CHESTPLATE
    durability:
      max_custom_durability: 602
    equipment:
      id: ecbluemecharmor_purple
      legacy_armor_rendering_id: ecbluemecharmor_purple
      slot: CHEST
      slot_attribute_modifiers:
        armor: 7
        armorToughness: 3
  ecbluemechhelmet_purple:
    display_name: Bluemech Helmet (purple)
    resource:
      model_id: 2725
      model_path: auto_generated/ecbluemechhelmet_purple
      generate: false
      textures:
      - item/ec_elitearmorsvol6/ecbluemechhelmet_purple.png
      material: LEATHER_HELMET
    durability:
      max_custom_durability: 602
    equipment:
      id: ecbluemecharmor_purple
      legacy_armor_rendering_id: ecbluemecharmor_purple
      slot: HEAD
      slot_attribute_modifiers:
        armor: 4
        armorToughness: 3
  ecbluemechlegs_purple:
    display_name: Bluemech Leggings (purple)
    resource:
      model_id: 2726
      model_path: auto_generated/ecbluemechlegs_purple
      generate: false
      textures:
      - item/ec_elitearmorsvol6/ecbluemechleggings_purple.png
      material: LEATHER_LEGGINGS
    durability:
      max_custom_durability: 602
    equipment:
      id: ecbluemecharmor_purple
      legacy_armor_rendering_id: ecbluemecharmor_purple
      slot: LEGS
      slot_attribute_modifiers:
        armor: 6
        armorToughness: 3
  ecbluemechboots_purple:
    display_name: Bluemech Boots (purple)
    resource:
      model_id: 2723
      model_path: auto_generated/ecbluemechboots_purple
      generate: false
      textures:
      - item/ec_elitearmorsvol6/ecbluemechboots_purple.png
      material: LEATHER_BOOTS
    durability:
      max_custom_durability: 602
    equipment:
      id: ecbluemecharmor_purple
      legacy_armor_rendering_id: ecbluemecharmor_purple
      slot: FEET
      slot_attribute_modifiers:
        armor: 4
        armorToughness: 3
  eclavabeastchest_purple:
    display_name: Lavabeast Chestplate (purple)
    resource:
      model_id: 2728
      model_path: auto_generated/eclavabeastchest_purple
      generate: false
      textures:
      - item/ec_elitearmorsvol6/eclavabeastchest_purple.png
      material: LEATHER_CHESTPLATE
    durability:
      max_custom_durability: 602
    equipment:
      id: eclavabeastarmor_purple
      legacy_armor_rendering_id: eclavabeastarmor_purple
      slot: CHEST
      slot_attribute_modifiers:
        armor: 7
        armorToughness: 3
  eclavabeasthelmet_purple:
    display_name: Lavabeast Helmet (purple)
    resource:
      model_id: 2729
      model_path: auto_generated/eclavabeasthelmet_purple
      generate: false
      textures:
      - item/ec_elitearmorsvol6/eclavabeasthelmet_purple.png
      material: LEATHER_HELMET
    durability:
      max_custom_durability: 602
    equipment:
      id: eclavabeastarmor_purple
      legacy_armor_rendering_id: eclavabeastarmor_purple
      slot: HEAD
      slot_attribute_modifiers:
        armor: 4
        armorToughness: 3
  eclavabeastlegs_purple:
    display_name: Lavabeast Leggings (purple)
    resource:
      model_id: 2730
      model_path: auto_generated/eclavabeastlegs_purple
      generate: false
      textures:
      - item/ec_elitearmorsvol6/eclavabeastleggings_purple.png
      material: LEATHER_LEGGINGS
    durability:
      max_custom_durability: 602
    equipment:
      id: eclavabeastarmor_purple
      legacy_armor_rendering_id: eclavabeastarmor_purple
      slot: LEGS
      slot_attribute_modifiers:
        armor: 6
        armorToughness: 3
  eclavabeastboots_purple:
    display_name: Lavabeast Boots (purple)
    resource:
      model_id: 2727
      model_path: auto_generated/eclavabeastboots_purple
      generate: false
      textures:
      - item/ec_elitearmorsvol6/eclavabeastboots_purple.png
      material: LEATHER_BOOTS
    durability:
      max_custom_durability: 602
    equipment:
      id: eclavabeastarmor_purple
      legacy_armor_rendering_id: eclavabeastarmor_purple
      slot: FEET
      slot_attribute_modifiers:
        armor: 4
        armorToughness: 3
