info:
  namespace: ec_elitearmors
armors_rendering:
  ecrubyarmor_cyan:
    color: '#5cec38'
    layer_1: armor/ec_elitearmorsvol6/ecrubyarmor_cyan
    layer_2: armor/ec_elitearmorsvol6/ecrubyarmor_cyan_2
    emissive_1: armor/ec_elitearmorsvol6/ecrubyarmore_1
    emissive_2: armor/ec_elitearmorsvol6/ecrubyarmore_2
    use_color: false
  eclightknightarmor_cyan:
    color: '#66f6ba'
    layer_1: armor/ec_elitearmorsvol6/eclightknightarmor_cyan
    layer_2: armor/ec_elitearmorsvol6/eclightknightarmor_cyan_2
    emissive_1: armor/ec_elitearmorsvol6/eclightknightarmore_1
    emissive_2: armor/ec_elitearmorsvol6/eclightknightarmore_2
    use_color: false
  ecbluemecharmor_cyan:
    color: '#87dfc3'
    layer_1: armor/ec_elitearmorsvol6/ecbluemecharmor_cyan
    layer_2: armor/ec_elitearmorsvol6/ecbluemecharmor_cyan_2
    emissive_1: armor/ec_elitearmorsvol6/ecbluemecharmore_1
    emissive_2: armor/ec_elitearmorsvol6/ecbluemecharmore_2
    use_color: false
  eclavabeastarmor_cyan:
    color: '#28a7fb'
    layer_1: armor/ec_elitearmorsvol6/eclavabeastarmor_cyan
    layer_2: armor/ec_elitearmorsvol6/eclavabeastarmor_cyan_2
    emissive_1: armor/ec_elitearmorsvol6/eclavabeastarmore_1
    emissive_2: armor/ec_elitearmorsvol6/eclavabeastarmore_2
    use_color: false
equipments:
  ecrubyarmor_cyan:
    layer_1: armor/ec_elitearmorsvol6/ecrubyarmor_cyan
    layer_2: armor/ec_elitearmorsvol6/ecrubyarmor_cyan_2
  eclightknightarmor_cyan:
    layer_1: armor/ec_elitearmorsvol6/eclightknightarmor_cyan
    layer_2: armor/ec_elitearmorsvol6/eclightknightarmor_cyan_2
  ecbluemecharmor_cyan:
    layer_1: armor/ec_elitearmorsvol6/ecbluemecharmor_cyan
    layer_2: armor/ec_elitearmorsvol6/ecbluemecharmor_cyan_2
  eclavabeastarmor_cyan:
    layer_1: armor/ec_elitearmorsvol6/eclavabeastarmor_cyan
    layer_2: armor/ec_elitearmorsvol6/eclavabeastarmor_cyan_2
items:
  ecrubychest_cyan:
    display_name: Ruby Chestplate (cyan)
    resource:
      model_id: 2640
      model_path: auto_generated/ecrubychest_cyan
      generate: false
      textures:
      - item/ec_elitearmorsvol6/ecrubychest_cyan.png
      material: LEATHER_CHESTPLATE
    durability:
      max_custom_durability: 602
    equipment:
      id: ecrubyarmor_cyan
      legacy_armor_rendering_id: ecrubyarmor_cyan
      slot: CHEST
      slot_attribute_modifiers:
        armor: 7
        armorToughness: 3
  ecrubyhelmet_cyan:
    display_name: Ruby Helmet (cyan)
    resource:
      model_id: 2641
      model_path: auto_generated/ecrubyhelmet_cyan
      generate: false
      material: LEATHER_HELMET
    durability:
      max_custom_durability: 602
    equipment:
      id: ecrubyarmor_cyan
      legacy_armor_rendering_id: ecrubyarmor_cyan
      slot: HEAD
      slot_attribute_modifiers:
        armor: 4
        armorToughness: 3
  ecrubylegs_cyan:
    display_name: Ruby Leggings (cyan)
    resource:
      model_id: 2642
      model_path: auto_generated/ecrubylegs_cyan
      generate: false
      material: LEATHER_LEGGINGS
    durability:
      max_custom_durability: 602
    equipment:
      id: ecrubyarmor_cyan
      legacy_armor_rendering_id: ecrubyarmor_cyan
      slot: LEGS
      slot_attribute_modifiers:
        armor: 6
        armorToughness: 3
  ecrubyboots_cyan:
    display_name: Ruby Boots (cyan)
    resource:
      model_id: 2639
      model_path: auto_generated/ecrubyboots_cyan
      generate: false
      textures:
      - item/ec_elitearmorsvol6/ecrubyboots_cyan.png
      material: LEATHER_BOOTS
    durability:
      max_custom_durability: 602
    equipment:
      id: ecrubyarmor_cyan
      legacy_armor_rendering_id: ecrubyarmor_cyan
      slot: FEET
      slot_attribute_modifiers:
        armor: 4
        armorToughness: 3
  eclightknightchest_cyan:
    display_name: Lightknight Chestplate (cyan)
    resource:
      model_id: 2636
      model_path: auto_generated/eclightknightchest_cyan
      generate: false
      textures:
      - item/ec_elitearmorsvol6/eclightknightchest_cyan.png
      material: LEATHER_CHESTPLATE
    durability:
      max_custom_durability: 602
    equipment:
      id: eclightknightarmor_cyan
      legacy_armor_rendering_id: eclightknightarmor_cyan
      slot: CHEST
      slot_attribute_modifiers:
        armor: 7
        armorToughness: 3
  eclightknighthelmet_cyan:
    display_name: Lightknight Helmet (cyan)
    resource:
      model_id: 2637
      model_path: auto_generated/eclightknighthelmet_cyan
      generate: false
      textures:
      - item/ec_elitearmorsvol6/eclightknighthelmet_cyan.png
      material: LEATHER_HELMET
    durability:
      max_custom_durability: 602
    equipment:
      id: eclightknightarmor_cyan
      legacy_armor_rendering_id: eclightknightarmor_cyan
      slot: HEAD
      slot_attribute_modifiers:
        armor: 4
        armorToughness: 3
  eclightknightlegs_cyan:
    display_name: Lightknight Leggings (cyan)
    resource:
      model_id: 2638
      model_path: auto_generated/eclightknightlegs_cyan
      generate: false
      textures:
      - item/ec_elitearmorsvol6/eclightknightleggings_cyan.png
      material: LEATHER_LEGGINGS
    durability:
      max_custom_durability: 602
    equipment:
      id: eclightknightarmor_cyan
      legacy_armor_rendering_id: eclightknightarmor_cyan
      slot: LEGS
      slot_attribute_modifiers:
        armor: 6
        armorToughness: 3
  eclightknightboots_cyan:
    display_name: Lightknight Boots (cyan)
    resource:
      model_id: 2635
      model_path: auto_generated/eclightknightboots_cyan
      generate: false
      textures:
      - item/ec_elitearmorsvol6/eclightknightboots_cyan.png
      material: LEATHER_BOOTS
    durability:
      max_custom_durability: 602
    equipment:
      id: eclightknightarmor_cyan
      legacy_armor_rendering_id: eclightknightarmor_cyan
      slot: FEET
      slot_attribute_modifiers:
        armor: 4
        armorToughness: 3
  ecbluemechchest_cyan:
    display_name: Bluemech Chestplate (cyan)
    resource:
      model_id: 2628
      model_path: auto_generated/ecbluemechchest_cyan
      generate: false
      textures:
      - item/ec_elitearmorsvol6/ecbluemechchest_cyan.png
      material: LEATHER_CHESTPLATE
    durability:
      max_custom_durability: 602
    equipment:
      id: ecbluemecharmor_cyan
      legacy_armor_rendering_id: ecbluemecharmor_cyan
      slot: CHEST
      slot_attribute_modifiers:
        armor: 7
        armorToughness: 3
  ecbluemechhelmet_cyan:
    display_name: Bluemech Helmet (cyan)
    resource:
      model_id: 2629
      model_path: auto_generated/ecbluemechhelmet_cyan
      generate: false
      textures:
      - item/ec_elitearmorsvol6/ecbluemechhelmet_cyan.png
      material: LEATHER_HELMET
    durability:
      max_custom_durability: 602
    equipment:
      id: ecbluemecharmor_cyan
      legacy_armor_rendering_id: ecbluemecharmor_cyan
      slot: HEAD
      slot_attribute_modifiers:
        armor: 4
        armorToughness: 3
  ecbluemechlegs_cyan:
    display_name: Bluemech Leggings (cyan)
    resource:
      model_id: 2630
      model_path: auto_generated/ecbluemechlegs_cyan
      generate: false
      textures:
      - item/ec_elitearmorsvol6/ecbluemechleggings_cyan.png
      material: LEATHER_LEGGINGS
    durability:
      max_custom_durability: 602
    equipment:
      id: ecbluemecharmor_cyan
      legacy_armor_rendering_id: ecbluemecharmor_cyan
      slot: LEGS
      slot_attribute_modifiers:
        armor: 6
        armorToughness: 3
  ecbluemechboots_cyan:
    display_name: Bluemech Boots (cyan)
    resource:
      model_id: 2627
      model_path: auto_generated/ecbluemechboots_cyan
      generate: false
      textures:
      - item/ec_elitearmorsvol6/ecbluemechboots_cyan.png
      material: LEATHER_BOOTS
    durability:
      max_custom_durability: 602
    equipment:
      id: ecbluemecharmor_cyan
      legacy_armor_rendering_id: ecbluemecharmor_cyan
      slot: FEET
      slot_attribute_modifiers:
        armor: 4
        armorToughness: 3
  eclavabeastchest_cyan:
    display_name: Lavabeast Chestplate (cyan)
    resource:
      model_id: 2632
      model_path: auto_generated/eclavabeastchest_cyan
      generate: false
      textures:
      - item/ec_elitearmorsvol6/eclavabeastchest_cyan.png
      material: LEATHER_CHESTPLATE
    durability:
      max_custom_durability: 602
    equipment:
      id: eclavabeastarmor_cyan
      legacy_armor_rendering_id: eclavabeastarmor_cyan
      slot: CHEST
      slot_attribute_modifiers:
        armor: 7
        armorToughness: 3
  eclavabeasthelmet_cyan:
    display_name: Lavabeast Helmet (cyan)
    resource:
      model_id: 2633
      model_path: auto_generated/eclavabeasthelmet_cyan
      generate: false
      textures:
      - item/ec_elitearmorsvol6/eclavabeasthelmet_cyan.png
      material: LEATHER_HELMET
    durability:
      max_custom_durability: 602
    equipment:
      id: eclavabeastarmor_cyan
      legacy_armor_rendering_id: eclavabeastarmor_cyan
      slot: HEAD
      slot_attribute_modifiers:
        armor: 4
        armorToughness: 3
  eclavabeastlegs_cyan:
    display_name: Lavabeast Leggings (cyan)
    resource:
      model_id: 2634
      model_path: auto_generated/eclavabeastlegs_cyan
      generate: false
      textures:
      - item/ec_elitearmorsvol6/eclavabeastleggings_cyan.png
      material: LEATHER_LEGGINGS
    durability:
      max_custom_durability: 602
    equipment:
      id: eclavabeastarmor_cyan
      legacy_armor_rendering_id: eclavabeastarmor_cyan
      slot: LEGS
      slot_attribute_modifiers:
        armor: 6
        armorToughness: 3
  eclavabeastboots_cyan:
    display_name: Lavabeast Boots (cyan)
    resource:
      model_id: 2631
      model_path: auto_generated/eclavabeastboots_cyan
      generate: false
      textures:
      - item/ec_elitearmorsvol6/eclavabeastboots_cyan.png
      material: LEATHER_BOOTS
    durability:
      max_custom_durability: 602
    equipment:
      id: eclavabeastarmor_cyan
      legacy_armor_rendering_id: eclavabeastarmor_cyan
      slot: FEET
      slot_attribute_modifiers:
        armor: 4
        armorToughness: 3
