info:
  namespace: elitecreatures
armors_rendering:
  witchcaster_animated_lightred:
    color: '#ffffda'
    layer_1: witchcaster_animated/armor/witchcasteranimated_armor_lightred_1
    layer_2: witchcaster_animated/armor/witchcasteranimated_armor_lightred_2
    use_color: false
equipments:
  witchcaster_animated_lightred:
    layer_1: witchcaster_animated/armor/witchcasteranimated_armor_lightred_1
    layer_2: witchcaster_animated/armor/witchcasteranimated_armor_lightred_2
items:
  witchcaster_animated_hat_lightred:
    display_name: DISPLAY (lightred)
    resource:
      material: PAPER
      model_path: witchcaster_animated/armor/hat_lightred
      model_id: 2237
      generate: false
    behaviours:
      hat: true
  witchcaster_animated_chestplate_lightred:
    display_name: DISPLAY (lightred)
    resource:
      model_path: witchcaster_animated/armor/chestplate_lightred
      model_id: 2236
      generate: false
      material: LEATHER_CHESTPLATE
    equipment:
      id: witchcaster_animated_lightred
      legacy_armor_rendering_id: witchcaster_animated_lightred
      slot: CHEST
  witchcaster_animated_leggings_lightred:
    display_name: DISPLAY (lightred)
    resource:
      model_path: witchcaster_animated/armor/leggings_lightred
      model_id: 2238
      generate: false
      material: LEATHER_LEGGINGS
    equipment:
      id: witchcaster_animated_lightred
      legacy_armor_rendering_id: witchcaster_animated_lightred
      slot: LEGS
  witchcaster_animated_boots_lightred:
    display_name: DISPLAY (lightred)
    resource:
      model_path: witchcaster_animated/armor/boots_lightred
      model_id: 2235
      generate: false
      material: LEATHER_BOOTS
    equipment:
      id: witchcaster_animated_lightred
      legacy_armor_rendering_id: witchcaster_animated_lightred
      slot: FEET
