info:
  namespace: elitecreatures
armors_rendering:
  witchcaster_animated_yellow:
    color: '#ffffd7'
    layer_1: witchcaster_animated/armor/witchcasteranimated_armor_yellow_1
    layer_2: witchcaster_animated/armor/witchcasteranimated_armor_yellow_2
    use_color: false
equipments:
  witchcaster_animated_yellow:
    layer_1: witchcaster_animated/armor/witchcasteranimated_armor_yellow_1
    layer_2: witchcaster_animated/armor/witchcasteranimated_armor_yellow_2
items:
  witchcaster_animated_hat_yellow:
    display_name: DISPLAY (yellow)
    resource:
      material: PAPER
      model_path: witchcaster_animated/armor/hat_yellow
      model_id: 2273
      generate: false
    behaviours:
      hat: true
  witchcaster_animated_chestplate_yellow:
    display_name: DISPLAY (yellow)
    resource:
      model_path: witchcaster_animated/armor/chestplate_yellow
      model_id: 2272
      generate: false
      material: LEATHER_CHESTPLATE
    equipment:
      id: witchcaster_animated_yellow
      legacy_armor_rendering_id: witchcaster_animated_yellow
      slot: CHEST
  witchcaster_animated_leggings_yellow:
    display_name: DISPLAY (yellow)
    resource:
      model_path: witchcaster_animated/armor/leggings_yellow
      model_id: 2274
      generate: false
      material: LEATHER_LEGGINGS
    equipment:
      id: witchcaster_animated_yellow
      legacy_armor_rendering_id: witchcaster_animated_yellow
      slot: LEGS
  witchcaster_animated_boots_yellow:
    display_name: DISPLAY (yellow)
    resource:
      model_path: witchcaster_animated/armor/boots_yellow
      model_id: 2271
      generate: false
      material: LEATHER_BOOTS
    equipment:
      id: witchcaster_animated_yellow
      legacy_armor_rendering_id: witchcaster_animated_yellow
      slot: FEET
