info:
  namespace: elitecreatures
armors_rendering:
  witchcaster_animated_darkblue:
    color: '#fffff5'
    layer_1: witchcaster_animated/armor/witchcasteranimated_armor_darkblue_1
    layer_2: witchcaster_animated/armor/witchcasteranimated_armor_darkblue_2
    use_color: false
equipments:
  witchcaster_animated_darkblue:
    layer_1: witchcaster_animated/armor/witchcasteranimated_armor_darkblue_1
    layer_2: witchcaster_animated/armor/witchcasteranimated_armor_darkblue_2
items:
  witchcaster_animated_hat_darkblue:
    display_name: DISPLAY (darkblue)
    resource:
      material: PAPER
      model_path: witchcaster_animated/armor/hat_darkblue
      model_id: 2309
      generate: false
    behaviours:
      hat: true
  witchcaster_animated_chestplate_darkblue:
    display_name: DISPLAY (darkblue)
    resource:
      model_path: witchcaster_animated/armor/chestplate_darkblue
      model_id: 2308
      generate: false
      material: LEATHER_CHESTPLATE
    equipment:
      id: witchcaster_animated_darkblue
      legacy_armor_rendering_id: witchcaster_animated_darkblue
      slot: CHEST
  witchcaster_animated_leggings_darkblue:
    display_name: DISPLAY (darkblue)
    resource:
      model_path: witchcaster_animated/armor/leggings_darkblue
      model_id: 2310
      generate: false
      material: LEATHER_LEGGINGS
    equipment:
      id: witchcaster_animated_darkblue
      legacy_armor_rendering_id: witchcaster_animated_darkblue
      slot: LEGS
  witchcaster_animated_boots_darkblue:
    display_name: DISPLAY (darkblue)
    resource:
      model_path: witchcaster_animated/armor/boots_darkblue
      model_id: 2307
      generate: false
      material: LEATHER_BOOTS
    equipment:
      id: witchcaster_animated_darkblue
      legacy_armor_rendering_id: witchcaster_animated_darkblue
      slot: FEET
