info:
  namespace: elitecreatures
armors_rendering:
  witchcaster_animated_lightgreen:
    color: '#ffffd5'
    layer_1: witchcaster_animated/armor/witchcasteranimated_armor_lightgreen_1
    layer_2: witchcaster_animated/armor/witchcasteranimated_armor_lightgreen_2
    use_color: false
equipments:
  witchcaster_animated_lightgreen:
    layer_1: witchcaster_animated/armor/witchcasteranimated_armor_lightgreen_1
    layer_2: witchcaster_animated/armor/witchcasteranimated_armor_lightgreen_2
items:
  witchcaster_animated_hat_lightgreen:
    display_name: DISPLAY (lightgreen)
    resource:
      material: PAPER
      model_path: witchcaster_animated/armor/hat_lightgreen
      model_id: 2281
      generate: false
    behaviours:
      hat: true
  witchcaster_animated_chestplate_lightgreen:
    display_name: DISPLAY (lightgreen)
    resource:
      model_path: witchcaster_animated/armor/chestplate_lightgreen
      model_id: 2280
      generate: false
      material: LEATHER_CHESTPLATE
    equipment:
      id: witchcaster_animated_lightgreen
      legacy_armor_rendering_id: witchcaster_animated_lightgreen
      slot: CHEST
  witchcaster_animated_leggings_lightgreen:
    display_name: DISPLAY (lightgreen)
    resource:
      model_path: witchcaster_animated/armor/leggings_lightgreen
      model_id: 2282
      generate: false
      material: LEATHER_LEGGINGS
    equipment:
      id: witchcaster_animated_lightgreen
      legacy_armor_rendering_id: witchcaster_animated_lightgreen
      slot: LEGS
  witchcaster_animated_boots_lightgreen:
    display_name: DISPLAY (lightgreen)
    resource:
      model_path: witchcaster_animated/armor/boots_lightgreen
      model_id: 2279
      generate: false
      material: LEATHER_BOOTS
    equipment:
      id: witchcaster_animated_lightgreen
      legacy_armor_rendering_id: witchcaster_animated_lightgreen
      slot: FEET
