info:
  namespace: elitecreatures
armors_rendering:
  witchcaster_animated_pink:
    color: '#fffffa'
    layer_1: witchcaster_animated/armor/witchcasteranimated_armor_pink_1
    layer_2: witchcaster_animated/armor/witchcasteranimated_armor_pink_2
    use_color: false
equipments:
  witchcaster_animated_pink:
    layer_1: witchcaster_animated/armor/witchcasteranimated_armor_pink_1
    layer_2: witchcaster_animated/armor/witchcasteranimated_armor_pink_2
items:
  witchcaster_animated_hat_pink:
    display_name: DISPLAY (pink)
    resource:
      material: PAPER
      model_path: witchcaster_animated/armor/hat_pink
      model_id: 2249
      generate: false
    behaviours:
      hat: true
  witchcaster_animated_chestplate_pink:
    display_name: DISPLAY (pink)
    resource:
      model_path: witchcaster_animated/armor/chestplate_pink
      model_id: 2248
      generate: false
      material: LEATHER_CHESTPLATE
    equipment:
      id: witchcaster_animated_pink
      legacy_armor_rendering_id: witchcaster_animated_pink
      slot: CHEST
  witchcaster_animated_leggings_pink:
    display_name: DISPLAY (pink)
    resource:
      model_path: witchcaster_animated/armor/leggings_pink
      model_id: 2250
      generate: false
      material: LEATHER_LEGGINGS
    equipment:
      id: witchcaster_animated_pink
      legacy_armor_rendering_id: witchcaster_animated_pink
      slot: LEGS
  witchcaster_animated_boots_pink:
    display_name: DISPLAY (pink)
    resource:
      model_path: witchcaster_animated/armor/boots_pink
      model_id: 2247
      generate: false
      material: LEATHER_BOOTS
    equipment:
      id: witchcaster_animated_pink
      legacy_armor_rendering_id: witchcaster_animated_pink
      slot: FEET
