info:
  namespace: elitecreatures
armors_rendering:
  witchcaster_animated_brown:
    color: '#ffffcd'
    layer_1: witchcaster_animated/armor/witchcasteranimated_armor_brown_1
    layer_2: witchcaster_animated/armor/witchcasteranimated_armor_brown_2
    use_color: false
equipments:
  witchcaster_animated_brown:
    layer_1: witchcaster_animated/armor/witchcasteranimated_armor_brown_1
    layer_2: witchcaster_animated/armor/witchcasteranimated_armor_brown_2
items:
  witchcaster_animated_hat_brown:
    display_name: DISPLAY (brown)
    resource:
      material: PAPER
      model_path: witchcaster_animated/armor/hat_brown
      model_id: 2265
      generate: false
    behaviours:
      hat: true
  witchcaster_animated_chestplate_brown:
    display_name: DISPLAY (brown)
    resource:
      model_path: witchcaster_animated/armor/chestplate_brown
      model_id: 2264
      generate: false
      material: LEATHER_CHESTPLATE
    equipment:
      id: witchcaster_animated_brown
      legacy_armor_rendering_id: witchcaster_animated_brown
      slot: CHEST
  witchcaster_animated_leggings_brown:
    display_name: DISPLAY (brown)
    resource:
      model_path: witchcaster_animated/armor/leggings_brown
      model_id: 2266
      generate: false
      material: LEATHER_LEGGINGS
    equipment:
      id: witchcaster_animated_brown
      legacy_armor_rendering_id: witchcaster_animated_brown
      slot: LEGS
  witchcaster_animated_boots_brown:
    display_name: DISPLAY (brown)
    resource:
      model_path: witchcaster_animated/armor/boots_brown
      model_id: 2263
      generate: false
      material: LEATHER_BOOTS
    equipment:
      id: witchcaster_animated_brown
      legacy_armor_rendering_id: witchcaster_animated_brown
      slot: FEET
