info:
  namespace: elitecreatures
armors_rendering:
  witchcaster_animated_blue:
    color: '#fffff3'
    layer_1: witchcaster_animated/armor/witchcasteranimated_armor_blue_1
    layer_2: witchcaster_animated/armor/witchcasteranimated_armor_blue_2
    use_color: false
equipments:
  witchcaster_animated_blue:
    layer_1: witchcaster_animated/armor/witchcasteranimated_armor_blue_1
    layer_2: witchcaster_animated/armor/witchcasteranimated_armor_blue_2
items:
  witchcaster_animated_hat_blue:
    display_name: DISPLAY (blue)
    resource:
      material: PAPER
      model_path: witchcaster_animated/armor/hat_blue
      model_id: 2305
      generate: false
    behaviours:
      hat: true
  witchcaster_animated_chestplate_blue:
    display_name: DISPLAY (blue)
    resource:
      model_path: witchcaster_animated/armor/chestplate_blue
      model_id: 2304
      generate: false
      material: LEATHER_CHESTPLATE
    equipment:
      id: witchcaster_animated_blue
      legacy_armor_rendering_id: witchcaster_animated_blue
      slot: CHEST
  witchcaster_animated_leggings_blue:
    display_name: DISPLAY (blue)
    resource:
      model_path: witchcaster_animated/armor/leggings_blue
      model_id: 2306
      generate: false
      material: LEATHER_LEGGINGS
    equipment:
      id: witchcaster_animated_blue
      legacy_armor_rendering_id: witchcaster_animated_blue
      slot: LEGS
  witchcaster_animated_boots_blue:
    display_name: DISPLAY (blue)
    resource:
      model_path: witchcaster_animated/armor/boots_blue
      model_id: 2303
      generate: false
      material: LEATHER_BOOTS
    equipment:
      id: witchcaster_animated_blue
      legacy_armor_rendering_id: witchcaster_animated_blue
      slot: FEET
