info:
  namespace: elitecreatures
armors_rendering:
  witchcaster_animated_darkred:
    color: '#ffffe2'
    layer_1: witchcaster_animated/armor/witchcasteranimated_armor_darkred_1
    layer_2: witchcaster_animated/armor/witchcasteranimated_armor_darkred_2
    use_color: false
equipments:
  witchcaster_animated_darkred:
    layer_1: witchcaster_animated/armor/witchcasteranimated_armor_darkred_1
    layer_2: witchcaster_animated/armor/witchcasteranimated_armor_darkred_2
items:
  witchcaster_animated_hat_darkred:
    display_name: DISPLAY (darkred)
    resource:
      material: PAPER
      model_path: witchcaster_animated/armor/hat_darkred
      model_id: 2245
      generate: false
    behaviours:
      hat: true
  witchcaster_animated_chestplate_darkred:
    display_name: DISPLAY (darkred)
    resource:
      model_path: witchcaster_animated/armor/chestplate_darkred
      model_id: 2244
      generate: false
      material: LEATHER_CHESTPLATE
    equipment:
      id: witchcaster_animated_darkred
      legacy_armor_rendering_id: witchcaster_animated_darkred
      slot: CHEST
  witchcaster_animated_leggings_darkred:
    display_name: DISPLAY (darkred)
    resource:
      model_path: witchcaster_animated/armor/leggings_darkred
      model_id: 2246
      generate: false
      material: LEATHER_LEGGINGS
    equipment:
      id: witchcaster_animated_darkred
      legacy_armor_rendering_id: witchcaster_animated_darkred
      slot: LEGS
  witchcaster_animated_boots_darkred:
    display_name: DISPLAY (darkred)
    resource:
      model_path: witchcaster_animated/armor/boots_darkred
      model_id: 2243
      generate: false
      material: LEATHER_BOOTS
    equipment:
      id: witchcaster_animated_darkred
      legacy_armor_rendering_id: witchcaster_animated_darkred
      slot: FEET
