info:
  namespace: elitecreatures
armors_rendering:
  witchcaster_animated_orange:
    color: '#ffffcc'
    layer_1: witchcaster_animated/armor/witchcasteranimated_armor_orange_1
    layer_2: witchcaster_animated/armor/witchcasteranimated_armor_orange_2
    use_color: false
equipments:
  witchcaster_animated_orange:
    layer_1: witchcaster_animated/armor/witchcasteranimated_armor_orange_1
    layer_2: witchcaster_animated/armor/witchcasteranimated_armor_orange_2
items:
  witchcaster_animated_hat_orange:
    display_name: DISPLAY (orange)
    resource:
      material: PAPER
      model_path: witchcaster_animated/armor/hat_orange
      model_id: 2257
      generate: false
    behaviours:
      hat: true
  witchcaster_animated_chestplate_orange:
    display_name: DISPLAY (orange)
    resource:
      model_path: witchcaster_animated/armor/chestplate_orange
      model_id: 2256
      generate: false
      material: LEATHER_CHESTPLATE
    equipment:
      id: witchcaster_animated_orange
      legacy_armor_rendering_id: witchcaster_animated_orange
      slot: CHEST
  witchcaster_animated_leggings_orange:
    display_name: DISPLAY (orange)
    resource:
      model_path: witchcaster_animated/armor/leggings_orange
      model_id: 2258
      generate: false
      material: LEATHER_LEGGINGS
    equipment:
      id: witchcaster_animated_orange
      legacy_armor_rendering_id: witchcaster_animated_orange
      slot: LEGS
  witchcaster_animated_boots_orange:
    display_name: DISPLAY (orange)
    resource:
      model_path: witchcaster_animated/armor/boots_orange
      model_id: 2255
      generate: false
      material: LEATHER_BOOTS
    equipment:
      id: witchcaster_animated_orange
      legacy_armor_rendering_id: witchcaster_animated_orange
      slot: FEET
