info:
  namespace: elitecreatures
armors_rendering:
  witchcaster_animated:
    color: '#ffffe6'
    layer_1: witchcaster_animated/armor/witchcasteranimated_armor_1
    layer_2: witchcaster_animated/armor/witchcasteranimated_armor_2
    use_color: false
equipments:
  witchcaster_animated:
    layer_1: witchcaster_animated/armor/witchcasteranimated_armor_1
    layer_2: witchcaster_animated/armor/witchcasteranimated_armor_2
items:
  witchcaster_animated_hat:
    display_name: DISPLAY
    resource:
      material: PAPER
      model_path: witchcaster_animated/armor/hat
      model_id: 2217
      generate: false
    behaviours:
      hat: true
  witchcaster_animated_chestplate:
    display_name: DISPLAY
    resource:
      model_path: witchcaster_animated/armor/chestplate
      model_id: 2216
      generate: false
      material: LEATHER_CHESTPLATE
    equipment:
      id: witchcaster_animated
      legacy_armor_rendering_id: witchcaster_animated
      slot: CHEST
  witchcaster_animated_leggings:
    display_name: DISPLAY
    resource:
      model_path: witchcaster_animated/armor/leggings
      model_id: 2218
      generate: false
      material: LEATHER_LEGGINGS
    equipment:
      id: witchcaster_animated
      legacy_armor_rendering_id: witchcaster_animated
      slot: LEGS
  witchcaster_animated_boots:
    display_name: DISPLAY
    resource:
      model_path: witchcaster_animated/armor/boots
      model_id: 2215
      generate: false
      material: LEATHER_BOOTS
    equipment:
      id: witchcaster_animated
      legacy_armor_rendering_id: witchcaster_animated
      slot: FEET
