info:
  namespace: elitecreatures
armors_rendering:
  witchcaster_animated_darkorange:
    color: '#ffffdc'
    layer_1: witchcaster_animated/armor/witchcasteranimated_armor_darkorange_1
    layer_2: witchcaster_animated/armor/witchcasteranimated_armor_darkorange_2
    use_color: false
equipments:
  witchcaster_animated_darkorange:
    layer_1: witchcaster_animated/armor/witchcasteranimated_armor_darkorange_1
    layer_2: witchcaster_animated/armor/witchcasteranimated_armor_darkorange_2
items:
  witchcaster_animated_hat_darkorange:
    display_name: DISPLAY (darkorange)
    resource:
      material: PAPER
      model_path: witchcaster_animated/armor/hat_darkorange
      model_id: 2261
      generate: false
    behaviours:
      hat: true
  witchcaster_animated_chestplate_darkorange:
    display_name: DISPLAY (darkorange)
    resource:
      model_path: witchcaster_animated/armor/chestplate_darkorange
      model_id: 2260
      generate: false
      material: LEATHER_CHESTPLATE
    equipment:
      id: witchcaster_animated_darkorange
      legacy_armor_rendering_id: witchcaster_animated_darkorange
      slot: CHEST
  witchcaster_animated_leggings_darkorange:
    display_name: DISPLAY (darkorange)
    resource:
      model_path: witchcaster_animated/armor/leggings_darkorange
      model_id: 2262
      generate: false
      material: LEATHER_LEGGINGS
    equipment:
      id: witchcaster_animated_darkorange
      legacy_armor_rendering_id: witchcaster_animated_darkorange
      slot: LEGS
  witchcaster_animated_boots_darkorange:
    display_name: DISPLAY (darkorange)
    resource:
      model_path: witchcaster_animated/armor/boots_darkorange
      model_id: 2259
      generate: false
      material: LEATHER_BOOTS
    equipment:
      id: witchcaster_animated_darkorange
      legacy_armor_rendering_id: witchcaster_animated_darkorange
      slot: FEET
