info:
  namespace: elitecreatures
armors_rendering:
  demonking_assortment_lightred:
    color: '#fffffb'
    layer_1: demonking_assortment/armor/demonkingassortment_armor_lightred_1
    layer_2: demonking_assortment/armor/demonkingassortment_armor_lightred_2
    use_color: false
equipments:
  demonking_assortment_lightred:
    layer_1: demonking_assortment/armor/demonkingassortment_armor_lightred_1
    layer_2: demonking_assortment/armor/demonkingassortment_armor_lightred_2
items:
  demonking_assortment_hat_lightred:
    display_name: demonkinghat (lightred)
    permission: demonking_assortment.lightred
    resource:
      model_id: 158
      material: PAPER
      model_path: demonking_assortment/armor/hat_lightred
      generate: false
    behaviours:
      hat: true
  demonking_assortment_chestplate_lightred:
    display_name: demonkingchestplate (lightred)
    resource:
      model_id: 157
      generate: false
      model_path: demonking_assortment/armor/chestplate_lightred
      material: LEATHER_CHESTPLATE
    equipment:
      id: demonking_assortment_lightred
      legacy_armor_rendering_id: demonking_assortment_lightred
      slot: CHEST
  demonking_assortment_leggings_lightred:
    display_name: demonkingleggings (lightred)
    resource:
      model_id: 159
      generate: false
      model_path: demonking_assortment/armor/leggings_lightred
      material: LEATHER_LEGGINGS
    equipment:
      id: demonking_assortment_lightred
      legacy_armor_rendering_id: demonking_assortment_lightred
      slot: LEGS
  demonking_assortment_boots_lightred:
    display_name: demonkingboots (lightred)
    resource:
      model_id: 156
      generate: false
      model_path: demonking_assortment/armor/boots_lightred
      material: LEATHER_BOOTS
    equipment:
      id: demonking_assortment_lightred
      legacy_armor_rendering_id: demonking_assortment_lightred
      slot: FEET
