info:
  namespace: elitecreatures
armors_rendering:
  demonking_assortment_lightgreen:
    color: '#fffff1'
    layer_1: demonking_assortment/armor/demonkingassortment_armor_lightgreen_1
    layer_2: demonking_assortment/armor/demonkingassortment_armor_lightgreen_2
    use_color: false
equipments:
  demonking_assortment_lightgreen:
    layer_1: demonking_assortment/armor/demonkingassortment_armor_lightgreen_1
    layer_2: demonking_assortment/armor/demonkingassortment_armor_lightgreen_2
items:
  demonking_assortment_hat_lightgreen:
    display_name: demonkinghat (lightgreen)
    permission: demonking_assortment.lightgreen
    resource:
      model_id: 202
      material: PAPER
      model_path: demonking_assortment/armor/hat_lightgreen
      generate: false
    behaviours:
      hat: true
  demonking_assortment_chestplate_lightgreen:
    display_name: demonkingchestplate (lightgreen)
    resource:
      model_id: 201
      generate: false
      model_path: demonking_assortment/armor/chestplate_lightgreen
      material: LEATHER_CHESTPLATE
    equipment:
      id: demonking_assortment_lightgreen
      legacy_armor_rendering_id: demonking_assortment_lightgreen
      slot: CHEST
  demonking_assortment_leggings_lightgreen:
    display_name: demonkingleggings (lightgreen)
    resource:
      model_id: 203
      generate: false
      model_path: demonking_assortment/armor/leggings_lightgreen
      material: LEATHER_LEGGINGS
    equipment:
      id: demonking_assortment_lightgreen
      legacy_armor_rendering_id: demonking_assortment_lightgreen
      slot: LEGS
  demonking_assortment_boots_lightgreen:
    display_name: demonkingboots (lightgreen)
    resource:
      model_id: 200
      generate: false
      model_path: demonking_assortment/armor/boots_lightgreen
      material: LEATHER_BOOTS
    equipment:
      id: demonking_assortment_lightgreen
      legacy_armor_rendering_id: demonking_assortment_lightgreen
      slot: FEET
