info:
  namespace: elitecreatures
armors_rendering:
  demonking_assortment_brown:
    color: '#ffffec'
    layer_1: demonking_assortment/armor/demonkingassortment_armor_brown_1
    layer_2: demonking_assortment/armor/demonkingassortment_armor_brown_2
    use_color: false
equipments:
  demonking_assortment_brown:
    layer_1: demonking_assortment/armor/demonkingassortment_armor_brown_1
    layer_2: demonking_assortment/armor/demonkingassortment_armor_brown_2
items:
  demonking_assortment_hat_brown:
    display_name: demonkinghat (brown)
    permission: demonking_assortment.brown
    resource:
      model_id: 186
      material: PAPER
      model_path: demonking_assortment/armor/hat_brown
      generate: false
    behaviours:
      hat: true
  demonking_assortment_chestplate_brown:
    display_name: demonkingchestplate (brown)
    resource:
      model_id: 185
      generate: false
      model_path: demonking_assortment/armor/chestplate_brown
      material: LEATHER_CHESTPLATE
    equipment:
      id: demonking_assortment_brown
      legacy_armor_rendering_id: demonking_assortment_brown
      slot: CHEST
  demonking_assortment_leggings_brown:
    display_name: demonkingleggings (brown)
    resource:
      model_id: 187
      generate: false
      model_path: demonking_assortment/armor/leggings_brown
      material: LEATHER_LEGGINGS
    equipment:
      id: demonking_assortment_brown
      legacy_armor_rendering_id: demonking_assortment_brown
      slot: LEGS
  demonking_assortment_boots_brown:
    display_name: demonkingboots (brown)
    resource:
      model_id: 184
      generate: false
      model_path: demonking_assortment/armor/boots_brown
      material: LEATHER_BOOTS
    equipment:
      id: demonking_assortment_brown
      legacy_armor_rendering_id: demonking_assortment_brown
      slot: FEET
