info:
  namespace: elitecreatures
armors_rendering:
  demonking_assortment_pink:
    color: '#fffff7'
    layer_1: demonking_assortment/armor/demonkingassortment_armor_pink_1
    layer_2: demonking_assortment/armor/demonkingassortment_armor_pink_2
    use_color: false
equipments:
  demonking_assortment_pink:
    layer_1: demonking_assortment/armor/demonkingassortment_armor_pink_1
    layer_2: demonking_assortment/armor/demonkingassortment_armor_pink_2
items:
  demonking_assortment_hat_pink:
    display_name: demonkinghat (pink)
    permission: demonking_assortment.pink
    resource:
      model_id: 170
      material: PAPER
      model_path: demonking_assortment/armor/hat_pink
      generate: false
    behaviours:
      hat: true
  demonking_assortment_chestplate_pink:
    display_name: demonkingchestplate (pink)
    resource:
      model_id: 169
      generate: false
      model_path: demonking_assortment/armor/chestplate_pink
      material: LEATHER_CHESTPLATE
    equipment:
      id: demonking_assortment_pink
      legacy_armor_rendering_id: demonking_assortment_pink
      slot: CHEST
  demonking_assortment_leggings_pink:
    display_name: demonkingleggings (pink)
    resource:
      model_id: 171
      generate: false
      model_path: demonking_assortment/armor/leggings_pink
      material: LEATHER_LEGGINGS
    equipment:
      id: demonking_assortment_pink
      legacy_armor_rendering_id: demonking_assortment_pink
      slot: LEGS
  demonking_assortment_boots_pink:
    display_name: demonkingboots (pink)
    resource:
      model_id: 168
      generate: false
      model_path: demonking_assortment/armor/boots_pink
      material: LEATHER_BOOTS
    equipment:
      id: demonking_assortment_pink
      legacy_armor_rendering_id: demonking_assortment_pink
      slot: FEET
