info:
  namespace: elitecreatures
armors_rendering:
  demonking_assortment_blue:
    color: '#fffff0'
    layer_1: demonking_assortment/armor/demonkingassortment_armor_blue_1
    layer_2: demonking_assortment/armor/demonkingassortment_armor_blue_2
    use_color: false
equipments:
  demonking_assortment_blue:
    layer_1: demonking_assortment/armor/demonkingassortment_armor_blue_1
    layer_2: demonking_assortment/armor/demonkingassortment_armor_blue_2
items:
  demonking_assortment_hat_blue:
    display_name: demonkinghat (blue)
    permission: demonking_assortment.blue
    resource:
      model_id: 226
      material: PAPER
      model_path: demonking_assortment/armor/hat_blue
      generate: false
    behaviours:
      hat: true
  demonking_assortment_chestplate_blue:
    display_name: demonkingchestplate (blue)
    resource:
      model_id: 225
      generate: false
      model_path: demonking_assortment/armor/chestplate_blue
      material: LEATHER_CHESTPLATE
    equipment:
      id: demonking_assortment_blue
      legacy_armor_rendering_id: demonking_assortment_blue
      slot: CHEST
  demonking_assortment_leggings_blue:
    display_name: demonkingleggings (blue)
    resource:
      model_id: 227
      generate: false
      model_path: demonking_assortment/armor/leggings_blue
      material: LEATHER_LEGGINGS
    equipment:
      id: demonking_assortment_blue
      legacy_armor_rendering_id: demonking_assortment_blue
      slot: LEGS
  demonking_assortment_boots_blue:
    display_name: demonkingboots (blue)
    resource:
      model_id: 224
      generate: false
      model_path: demonking_assortment/armor/boots_blue
      material: LEATHER_BOOTS
    equipment:
      id: demonking_assortment_blue
      legacy_armor_rendering_id: demonking_assortment_blue
      slot: FEET
