info:
  namespace: elitecreatures
armors_rendering:
  demonking_assortment_orange:
    color: '#ffffd8'
    layer_1: demonking_assortment/armor/demonkingassortment_armor_orange_1
    layer_2: demonking_assortment/armor/demonkingassortment_armor_orange_2
    use_color: false
equipments:
  demonking_assortment_orange:
    layer_1: demonking_assortment/armor/demonkingassortment_armor_orange_1
    layer_2: demonking_assortment/armor/demonkingassortment_armor_orange_2
items:
  demonking_assortment_hat_orange:
    display_name: demonkinghat (orange)
    permission: demonking_assortment.orange
    resource:
      model_id: 178
      material: PAPER
      model_path: demonking_assortment/armor/hat_orange
      generate: false
    behaviours:
      hat: true
  demonking_assortment_chestplate_orange:
    display_name: demonkingchestplate (orange)
    resource:
      model_id: 177
      generate: false
      model_path: demonking_assortment/armor/chestplate_orange
      material: LEATHER_CHESTPLATE
    equipment:
      id: demonking_assortment_orange
      legacy_armor_rendering_id: demonking_assortment_orange
      slot: CHEST
  demonking_assortment_leggings_orange:
    display_name: demonkingleggings (orange)
    resource:
      model_id: 179
      generate: false
      model_path: demonking_assortment/armor/leggings_orange
      material: LEATHER_LEGGINGS
    equipment:
      id: demonking_assortment_orange
      legacy_armor_rendering_id: demonking_assortment_orange
      slot: LEGS
  demonking_assortment_boots_orange:
    display_name: demonkingboots (orange)
    resource:
      model_id: 176
      generate: false
      model_path: demonking_assortment/armor/boots_orange
      material: LEATHER_BOOTS
    equipment:
      id: demonking_assortment_orange
      legacy_armor_rendering_id: demonking_assortment_orange
      slot: FEET
