info:
  namespace: elitecreatures
armors_rendering:
  demonking_assortment_darkred:
    color: '#ffffdd'
    layer_1: demonking_assortment/armor/demonkingassortment_armor_darkred_1
    layer_2: demonking_assortment/armor/demonkingassortment_armor_darkred_2
    use_color: false
equipments:
  demonking_assortment_darkred:
    layer_1: demonking_assortment/armor/demonkingassortment_armor_darkred_1
    layer_2: demonking_assortment/armor/demonkingassortment_armor_darkred_2
items:
  demonking_assortment_hat_darkred:
    display_name: demonkinghat (darkred)
    permission: demonking_assortment.darkred
    resource:
      model_id: 166
      material: PAPER
      model_path: demonking_assortment/armor/hat_darkred
      generate: false
    behaviours:
      hat: true
  demonking_assortment_chestplate_darkred:
    display_name: demonkingchestplate (darkred)
    resource:
      model_id: 165
      generate: false
      model_path: demonking_assortment/armor/chestplate_darkred
      material: LEATHER_CHESTPLATE
    equipment:
      id: demonking_assortment_darkred
      legacy_armor_rendering_id: demonking_assortment_darkred
      slot: CHEST
  demonking_assortment_leggings_darkred:
    display_name: demonkingleggings (darkred)
    resource:
      model_id: 167
      generate: false
      model_path: demonking_assortment/armor/leggings_darkred
      material: LEATHER_LEGGINGS
    equipment:
      id: demonking_assortment_darkred
      legacy_armor_rendering_id: demonking_assortment_darkred
      slot: LEGS
  demonking_assortment_boots_darkred:
    display_name: demonkingboots (darkred)
    resource:
      model_id: 164
      generate: false
      model_path: demonking_assortment/armor/boots_darkred
      material: LEATHER_BOOTS
    equipment:
      id: demonking_assortment_darkred
      legacy_armor_rendering_id: demonking_assortment_darkred
      slot: FEET
