info:
  namespace: elitecreatures
armors_rendering:
  demonking_assortment_darkpink:
    color: '#ffffe3'
    layer_1: demonking_assortment/armor/demonkingassortment_armor_darkpink_1
    layer_2: demonking_assortment/armor/demonkingassortment_armor_darkpink_2
    use_color: false
equipments:
  demonking_assortment_darkpink:
    layer_1: demonking_assortment/armor/demonkingassortment_armor_darkpink_1
    layer_2: demonking_assortment/armor/demonkingassortment_armor_darkpink_2
items:
  demonking_assortment_hat_darkpink:
    display_name: demonkinghat (darkpink)
    permission: demonking_assortment.darkpink
    resource:
      model_id: 174
      material: PAPER
      model_path: demonking_assortment/armor/hat_darkpink
      generate: false
    behaviours:
      hat: true
  demonking_assortment_chestplate_darkpink:
    display_name: demonkingchestplate (darkpink)
    resource:
      model_id: 173
      generate: false
      model_path: demonking_assortment/armor/chestplate_darkpink
      material: LEATHER_CHESTPLATE
    equipment:
      id: demonking_assortment_darkpink
      legacy_armor_rendering_id: demonking_assortment_darkpink
      slot: CHEST
  demonking_assortment_leggings_darkpink:
    display_name: demonkingleggings (darkpink)
    resource:
      model_id: 175
      generate: false
      model_path: demonking_assortment/armor/leggings_darkpink
      material: LEATHER_LEGGINGS
    equipment:
      id: demonking_assortment_darkpink
      legacy_armor_rendering_id: demonking_assortment_darkpink
      slot: LEGS
  demonking_assortment_boots_darkpink:
    display_name: demonkingboots (darkpink)
    resource:
      model_id: 172
      generate: false
      model_path: demonking_assortment/armor/boots_darkpink
      material: LEATHER_BOOTS
    equipment:
      id: demonking_assortment_darkpink
      legacy_armor_rendering_id: demonking_assortment_darkpink
      slot: FEET
