info:
  namespace: elitecreatures
armors_rendering:
  medieval_armor_set_heavy_armor_brown:
    color: '#5520bb'
    layer_1: medieval_armor_set/heavy_armor_layer_brown_1
    layer_2: medieval_armor_set/heavy_armor_layer_brown_2
    use_color: false
  medieval_armor_set_light_armor_brown:
    color: '#5520bc'
    layer_1: medieval_armor_set/light_armor_layer_brown_1
    layer_2: medieval_armor_set/light_armor_layer_brown_2
    use_color: false
  medieval_armor_set_medium_armor_brown:
    color: '#5520bd'
    layer_1: medieval_armor_set/medium_armor_layer_brown_1
    layer_2: medieval_armor_set/medium_armor_layer_brown_2
    use_color: false
  medieval_armor_set_wizard_armor_brown:
    color: '#5520be'
    layer_1: medieval_armor_set/wizard_armor_layer_brown_1
    layer_2: medieval_armor_set/wizard_armor_layer_brown_2
    use_color: false
equipments:
  medieval_armor_set_heavy_armor_brown:
    layer_1: medieval_armor_set/heavy_armor_layer_brown_1
    layer_2: medieval_armor_set/heavy_armor_layer_brown_2
  medieval_armor_set_light_armor_brown:
    layer_1: medieval_armor_set/light_armor_layer_brown_1
    layer_2: medieval_armor_set/light_armor_layer_brown_2
  medieval_armor_set_medium_armor_brown:
    layer_1: medieval_armor_set/medium_armor_layer_brown_1
    layer_2: medieval_armor_set/medium_armor_layer_brown_2
  medieval_armor_set_wizard_armor_brown:
    layer_1: medieval_armor_set/wizard_armor_layer_brown_1
    layer_2: medieval_armor_set/wizard_armor_layer_brown_2
items:
  medieval_armor_set_heavy_helmet_brown:
    display_name: Heavy Helmet (brown)
    resource:
      model_id: 600
      generate: false
      model_path: medieval_armor_set/heavy_helmet_brown
      material: LEATHER_HELMET
    equipment:
      id: medieval_armor_set_heavy_armor_brown
      legacy_armor_rendering_id: medieval_armor_set_heavy_armor_brown
      slot: HEAD
  medieval_armor_set_heavy_chestplate_brown:
    display_name: Heavy Chestplate (brown)
    resource:
      model_id: 599
      model_path: medieval_armor_set/heavy_chestplate_brown
      generate: false
      material: LEATHER_CHESTPLATE
    equipment:
      id: medieval_armor_set_heavy_armor_brown
      legacy_armor_rendering_id: medieval_armor_set_heavy_armor_brown
      slot: CHEST
  medieval_armor_set_heavy_leggings_brown:
    display_name: Heavy Leggings (brown)
    resource:
      model_id: 601
      model_path: medieval_armor_set/heavy_leggings_brown
      generate: false
      material: LEATHER_LEGGINGS
    equipment:
      id: medieval_armor_set_heavy_armor_brown
      legacy_armor_rendering_id: medieval_armor_set_heavy_armor_brown
      slot: LEGS
  medieval_armor_set_heavy_boots_brown:
    display_name: Heavy Boots (brown)
    resource:
      model_id: 598
      model_path: medieval_armor_set/heavy_boots_brown
      generate: false
      material: LEATHER_BOOTS
    equipment:
      id: medieval_armor_set_heavy_armor_brown
      legacy_armor_rendering_id: medieval_armor_set_heavy_armor_brown
      slot: FEET
  medieval_armor_set_light_helmet_brown:
    display_name: Light Helmet (brown)
    resource:
      model_id: 604
      model_path: medieval_armor_set/light_helmet_brown
      generate: false
      material: LEATHER_HELMET
    equipment:
      id: medieval_armor_set_light_armor_brown
      legacy_armor_rendering_id: medieval_armor_set_light_armor_brown
      slot: HEAD
  medieval_armor_set_light_chestplate_brown:
    display_name: Light Chestplate (brown)
    resource:
      model_id: 603
      model_path: medieval_armor_set/light_chestplate_brown
      generate: false
      material: LEATHER_CHESTPLATE
    equipment:
      id: medieval_armor_set_light_armor_brown
      legacy_armor_rendering_id: medieval_armor_set_light_armor_brown
      slot: CHEST
  medieval_armor_set_light_leggings_brown:
    display_name: Light Leggings (brown)
    resource:
      model_id: 605
      model_path: medieval_armor_set/light_leggings_brown
      generate: false
      material: LEATHER_LEGGINGS
    equipment:
      id: medieval_armor_set_light_armor_brown
      legacy_armor_rendering_id: medieval_armor_set_light_armor_brown
      slot: LEGS
  medieval_armor_set_light_boots_brown:
    display_name: Light Boots (brown)
    resource:
      model_id: 602
      model_path: medieval_armor_set/light_boots_brown
      generate: false
      material: LEATHER_BOOTS
    equipment:
      id: medieval_armor_set_light_armor_brown
      legacy_armor_rendering_id: medieval_armor_set_light_armor_brown
      slot: FEET
  medieval_armor_set_medium_helmet_brown:
    display_name: Medium Helmet (brown)
    resource:
      model_id: 608
      model_path: medieval_armor_set/medium_helmet_brown
      generate: false
      material: LEATHER_HELMET
    equipment:
      id: medieval_armor_set_medium_armor_brown
      legacy_armor_rendering_id: medieval_armor_set_medium_armor_brown
      slot: HEAD
  medieval_armor_set_medium_chestplate_brown:
    display_name: Medium Chestplate (brown)
    resource:
      model_id: 607
      model_path: medieval_armor_set/medium_chestplate_brown
      generate: false
      material: LEATHER_CHESTPLATE
    equipment:
      id: medieval_armor_set_medium_armor_brown
      legacy_armor_rendering_id: medieval_armor_set_medium_armor_brown
      slot: CHEST
  medieval_armor_set_medium_leggings_brown:
    display_name: Medium Leggings (brown)
    resource:
      model_id: 609
      model_path: medieval_armor_set/medium_leggings_brown
      generate: false
      material: LEATHER_LEGGINGS
    equipment:
      id: medieval_armor_set_medium_armor_brown
      legacy_armor_rendering_id: medieval_armor_set_medium_armor_brown
      slot: LEGS
  medieval_armor_set_medium_boots_brown:
    display_name: Medium Boots (brown)
    resource:
      model_id: 606
      model_path: medieval_armor_set/medium_boots_brown
      generate: false
      material: LEATHER_BOOTS
    equipment:
      id: medieval_armor_set_medium_armor_brown
      legacy_armor_rendering_id: medieval_armor_set_medium_armor_brown
      slot: FEET
  medieval_armor_set_wizard_helmet_brown:
    display_name: Wizard Helmet (brown)
    resource:
      model_id: 612
      model_path: medieval_armor_set/wizard_helmet_brown
      generate: false
      material: LEATHER_HELMET
    equipment:
      id: medieval_armor_set_wizard_armor_brown
      legacy_armor_rendering_id: medieval_armor_set_wizard_armor_brown
      slot: HEAD
  medieval_armor_set_wizard_chestplate_brown:
    display_name: Wizard Chestplate (brown)
    resource:
      model_id: 611
      model_path: medieval_armor_set/wizard_chestplate_brown
      generate: false
      material: LEATHER_CHESTPLATE
    equipment:
      id: medieval_armor_set_wizard_armor_brown
      legacy_armor_rendering_id: medieval_armor_set_wizard_armor_brown
      slot: CHEST
  medieval_armor_set_wizard_leggings_brown:
    display_name: Wizard Leggings (brown)
    resource:
      model_id: 613
      model_path: medieval_armor_set/wizard_leggings_brown
      generate: false
      material: LEATHER_LEGGINGS
    equipment:
      id: medieval_armor_set_wizard_armor_brown
      legacy_armor_rendering_id: medieval_armor_set_wizard_armor_brown
      slot: LEGS
  medieval_armor_set_wizard_boots_brown:
    display_name: Wizard Boots (brown)
    resource:
      model_id: 610
      model_path: medieval_armor_set/wizard_boots_brown
      generate: false
      material: LEATHER_BOOTS
    equipment:
      id: medieval_armor_set_wizard_armor_brown
      legacy_armor_rendering_id: medieval_armor_set_wizard_armor_brown
      slot: FEET
