info:
  namespace: elitecreatures
armors_rendering:
  medieval_armor_set_heavy_armor_teal:
    color: '#5520ab'
    layer_1: medieval_armor_set/heavy_armor_layer_teal_1
    layer_2: medieval_armor_set/heavy_armor_layer_teal_2
    use_color: false
  medieval_armor_set_light_armor_teal:
    color: '#5520ac'
    layer_1: medieval_armor_set/light_armor_layer_teal_1
    layer_2: medieval_armor_set/light_armor_layer_teal_2
    use_color: false
  medieval_armor_set_medium_armor_teal:
    color: '#5520ad'
    layer_1: medieval_armor_set/medium_armor_layer_teal_1
    layer_2: medieval_armor_set/medium_armor_layer_teal_2
    use_color: false
  medieval_armor_set_wizard_armor_teal:
    color: '#5520ae'
    layer_1: medieval_armor_set/wizard_armor_layer_teal_1
    layer_2: medieval_armor_set/wizard_armor_layer_teal_2
    use_color: false
equipments:
  medieval_armor_set_heavy_armor_teal:
    layer_1: medieval_armor_set/heavy_armor_layer_teal_1
    layer_2: medieval_armor_set/heavy_armor_layer_teal_2
  medieval_armor_set_light_armor_teal:
    layer_1: medieval_armor_set/light_armor_layer_teal_1
    layer_2: medieval_armor_set/light_armor_layer_teal_2
  medieval_armor_set_medium_armor_teal:
    layer_1: medieval_armor_set/medium_armor_layer_teal_1
    layer_2: medieval_armor_set/medium_armor_layer_teal_2
  medieval_armor_set_wizard_armor_teal:
    layer_1: medieval_armor_set/wizard_armor_layer_teal_1
    layer_2: medieval_armor_set/wizard_armor_layer_teal_2
items:
  medieval_armor_set_heavy_helmet_teal:
    display_name: Heavy Helmet (teal)
    resource:
      model_id: 728
      generate: false
      model_path: medieval_armor_set/heavy_helmet_teal
      material: LEATHER_HELMET
    equipment:
      id: medieval_armor_set_heavy_armor_teal
      legacy_armor_rendering_id: medieval_armor_set_heavy_armor_teal
      slot: HEAD
  medieval_armor_set_heavy_chestplate_teal:
    display_name: Heavy Chestplate (teal)
    resource:
      model_id: 727
      model_path: medieval_armor_set/heavy_chestplate_teal
      generate: false
      material: LEATHER_CHESTPLATE
    equipment:
      id: medieval_armor_set_heavy_armor_teal
      legacy_armor_rendering_id: medieval_armor_set_heavy_armor_teal
      slot: CHEST
  medieval_armor_set_heavy_leggings_teal:
    display_name: Heavy Leggings (teal)
    resource:
      model_id: 729
      model_path: medieval_armor_set/heavy_leggings_teal
      generate: false
      material: LEATHER_LEGGINGS
    equipment:
      id: medieval_armor_set_heavy_armor_teal
      legacy_armor_rendering_id: medieval_armor_set_heavy_armor_teal
      slot: LEGS
  medieval_armor_set_heavy_boots_teal:
    display_name: Heavy Boots (teal)
    resource:
      model_id: 726
      model_path: medieval_armor_set/heavy_boots_teal
      generate: false
      material: LEATHER_BOOTS
    equipment:
      id: medieval_armor_set_heavy_armor_teal
      legacy_armor_rendering_id: medieval_armor_set_heavy_armor_teal
      slot: FEET
  medieval_armor_set_light_helmet_teal:
    display_name: Light Helmet (teal)
    resource:
      model_id: 732
      model_path: medieval_armor_set/light_helmet_teal
      generate: false
      material: LEATHER_HELMET
    equipment:
      id: medieval_armor_set_light_armor_teal
      legacy_armor_rendering_id: medieval_armor_set_light_armor_teal
      slot: HEAD
  medieval_armor_set_light_chestplate_teal:
    display_name: Light Chestplate (teal)
    resource:
      model_id: 731
      model_path: medieval_armor_set/light_chestplate_teal
      generate: false
      material: LEATHER_CHESTPLATE
    equipment:
      id: medieval_armor_set_light_armor_teal
      legacy_armor_rendering_id: medieval_armor_set_light_armor_teal
      slot: CHEST
  medieval_armor_set_light_leggings_teal:
    display_name: Light Leggings (teal)
    resource:
      model_id: 733
      model_path: medieval_armor_set/light_leggings_teal
      generate: false
      material: LEATHER_LEGGINGS
    equipment:
      id: medieval_armor_set_light_armor_teal
      legacy_armor_rendering_id: medieval_armor_set_light_armor_teal
      slot: LEGS
  medieval_armor_set_light_boots_teal:
    display_name: Light Boots (teal)
    resource:
      model_id: 730
      model_path: medieval_armor_set/light_boots_teal
      generate: false
      material: LEATHER_BOOTS
    equipment:
      id: medieval_armor_set_light_armor_teal
      legacy_armor_rendering_id: medieval_armor_set_light_armor_teal
      slot: FEET
  medieval_armor_set_medium_helmet_teal:
    display_name: Medium Helmet (teal)
    resource:
      model_id: 736
      model_path: medieval_armor_set/medium_helmet_teal
      generate: false
      material: LEATHER_HELMET
    equipment:
      id: medieval_armor_set_medium_armor_teal
      legacy_armor_rendering_id: medieval_armor_set_medium_armor_teal
      slot: HEAD
  medieval_armor_set_medium_chestplate_teal:
    display_name: Medium Chestplate (teal)
    resource:
      model_id: 735
      model_path: medieval_armor_set/medium_chestplate_teal
      generate: false
      material: LEATHER_CHESTPLATE
    equipment:
      id: medieval_armor_set_medium_armor_teal
      legacy_armor_rendering_id: medieval_armor_set_medium_armor_teal
      slot: CHEST
  medieval_armor_set_medium_leggings_teal:
    display_name: Medium Leggings (teal)
    resource:
      model_id: 737
      model_path: medieval_armor_set/medium_leggings_teal
      generate: false
      material: LEATHER_LEGGINGS
    equipment:
      id: medieval_armor_set_medium_armor_teal
      legacy_armor_rendering_id: medieval_armor_set_medium_armor_teal
      slot: LEGS
  medieval_armor_set_medium_boots_teal:
    display_name: Medium Boots (teal)
    resource:
      model_id: 734
      model_path: medieval_armor_set/medium_boots_teal
      generate: false
      material: LEATHER_BOOTS
    equipment:
      id: medieval_armor_set_medium_armor_teal
      legacy_armor_rendering_id: medieval_armor_set_medium_armor_teal
      slot: FEET
  medieval_armor_set_wizard_helmet_teal:
    display_name: Wizard Helmet (teal)
    resource:
      model_id: 740
      model_path: medieval_armor_set/wizard_helmet_teal
      generate: false
      material: LEATHER_HELMET
    equipment:
      id: medieval_armor_set_wizard_armor_teal
      legacy_armor_rendering_id: medieval_armor_set_wizard_armor_teal
      slot: HEAD
  medieval_armor_set_wizard_chestplate_teal:
    display_name: Wizard Chestplate (teal)
    resource:
      model_id: 739
      model_path: medieval_armor_set/wizard_chestplate_teal
      generate: false
      material: LEATHER_CHESTPLATE
    equipment:
      id: medieval_armor_set_wizard_armor_teal
      legacy_armor_rendering_id: medieval_armor_set_wizard_armor_teal
      slot: CHEST
  medieval_armor_set_wizard_leggings_teal:
    display_name: Wizard Leggings (teal)
    resource:
      model_id: 741
      model_path: medieval_armor_set/wizard_leggings_teal
      generate: false
      material: LEATHER_LEGGINGS
    equipment:
      id: medieval_armor_set_wizard_armor_teal
      legacy_armor_rendering_id: medieval_armor_set_wizard_armor_teal
      slot: LEGS
  medieval_armor_set_wizard_boots_teal:
    display_name: Wizard Boots (teal)
    resource:
      model_id: 738
      model_path: medieval_armor_set/wizard_boots_teal
      generate: false
      material: LEATHER_BOOTS
    equipment:
      id: medieval_armor_set_wizard_armor_teal
      legacy_armor_rendering_id: medieval_armor_set_wizard_armor_teal
      slot: FEET
