info:
  namespace: elitecreatures
armors_rendering:
  medieval_armor_set_heavy_armor_darkpink:
    color: '#5520a7'
    layer_1: medieval_armor_set/heavy_armor_layer_darkpink_1
    layer_2: medieval_armor_set/heavy_armor_layer_darkpink_2
    use_color: false
  medieval_armor_set_light_armor_darkpink:
    color: '#5520a8'
    layer_1: medieval_armor_set/light_armor_layer_darkpink_1
    layer_2: medieval_armor_set/light_armor_layer_darkpink_2
    use_color: false
  medieval_armor_set_medium_armor_darkpink:
    color: '#5520a9'
    layer_1: medieval_armor_set/medium_armor_layer_darkpink_1
    layer_2: medieval_armor_set/medium_armor_layer_darkpink_2
    use_color: false
  medieval_armor_set_wizard_armor_darkpink:
    color: '#5520aa'
    layer_1: medieval_armor_set/wizard_armor_layer_darkpink_1
    layer_2: medieval_armor_set/wizard_armor_layer_darkpink_2
    use_color: false
equipments:
  medieval_armor_set_heavy_armor_darkpink:
    layer_1: medieval_armor_set/heavy_armor_layer_darkpink_1
    layer_2: medieval_armor_set/heavy_armor_layer_darkpink_2
  medieval_armor_set_light_armor_darkpink:
    layer_1: medieval_armor_set/light_armor_layer_darkpink_1
    layer_2: medieval_armor_set/light_armor_layer_darkpink_2
  medieval_armor_set_medium_armor_darkpink:
    layer_1: medieval_armor_set/medium_armor_layer_darkpink_1
    layer_2: medieval_armor_set/medium_armor_layer_darkpink_2
  medieval_armor_set_wizard_armor_darkpink:
    layer_1: medieval_armor_set/wizard_armor_layer_darkpink_1
    layer_2: medieval_armor_set/wizard_armor_layer_darkpink_2
items:
  medieval_armor_set_heavy_helmet_darkpink:
    display_name: Heavy Helmet (darkpink)
    resource:
      model_id: 552
      generate: false
      model_path: medieval_armor_set/heavy_helmet_darkpink
      material: LEATHER_HELMET
    equipment:
      id: medieval_armor_set_heavy_armor_darkpink
      legacy_armor_rendering_id: medieval_armor_set_heavy_armor_darkpink
      slot: HEAD
  medieval_armor_set_heavy_chestplate_darkpink:
    display_name: Heavy Chestplate (darkpink)
    resource:
      model_id: 551
      model_path: medieval_armor_set/heavy_chestplate_darkpink
      generate: false
      material: LEATHER_CHESTPLATE
    equipment:
      id: medieval_armor_set_heavy_armor_darkpink
      legacy_armor_rendering_id: medieval_armor_set_heavy_armor_darkpink
      slot: CHEST
  medieval_armor_set_heavy_leggings_darkpink:
    display_name: Heavy Leggings (darkpink)
    resource:
      model_id: 553
      model_path: medieval_armor_set/heavy_leggings_darkpink
      generate: false
      material: LEATHER_LEGGINGS
    equipment:
      id: medieval_armor_set_heavy_armor_darkpink
      legacy_armor_rendering_id: medieval_armor_set_heavy_armor_darkpink
      slot: LEGS
  medieval_armor_set_heavy_boots_darkpink:
    display_name: Heavy Boots (darkpink)
    resource:
      model_id: 550
      model_path: medieval_armor_set/heavy_boots_darkpink
      generate: false
      material: LEATHER_BOOTS
    equipment:
      id: medieval_armor_set_heavy_armor_darkpink
      legacy_armor_rendering_id: medieval_armor_set_heavy_armor_darkpink
      slot: FEET
  medieval_armor_set_light_helmet_darkpink:
    display_name: Light Helmet (darkpink)
    resource:
      model_id: 556
      model_path: medieval_armor_set/light_helmet_darkpink
      generate: false
      material: LEATHER_HELMET
    equipment:
      id: medieval_armor_set_light_armor_darkpink
      legacy_armor_rendering_id: medieval_armor_set_light_armor_darkpink
      slot: HEAD
  medieval_armor_set_light_chestplate_darkpink:
    display_name: Light Chestplate (darkpink)
    resource:
      model_id: 555
      model_path: medieval_armor_set/light_chestplate_darkpink
      generate: false
      material: LEATHER_CHESTPLATE
    equipment:
      id: medieval_armor_set_light_armor_darkpink
      legacy_armor_rendering_id: medieval_armor_set_light_armor_darkpink
      slot: CHEST
  medieval_armor_set_light_leggings_darkpink:
    display_name: Light Leggings (darkpink)
    resource:
      model_id: 557
      model_path: medieval_armor_set/light_leggings_darkpink
      generate: false
      material: LEATHER_LEGGINGS
    equipment:
      id: medieval_armor_set_light_armor_darkpink
      legacy_armor_rendering_id: medieval_armor_set_light_armor_darkpink
      slot: LEGS
  medieval_armor_set_light_boots_darkpink:
    display_name: Light Boots (darkpink)
    resource:
      model_id: 554
      model_path: medieval_armor_set/light_boots_darkpink
      generate: false
      material: LEATHER_BOOTS
    equipment:
      id: medieval_armor_set_light_armor_darkpink
      legacy_armor_rendering_id: medieval_armor_set_light_armor_darkpink
      slot: FEET
  medieval_armor_set_medium_helmet_darkpink:
    display_name: Medium Helmet (darkpink)
    resource:
      model_id: 560
      model_path: medieval_armor_set/medium_helmet_darkpink
      generate: false
      material: LEATHER_HELMET
    equipment:
      id: medieval_armor_set_medium_armor_darkpink
      legacy_armor_rendering_id: medieval_armor_set_medium_armor_darkpink
      slot: HEAD
  medieval_armor_set_medium_chestplate_darkpink:
    display_name: Medium Chestplate (darkpink)
    resource:
      model_id: 559
      model_path: medieval_armor_set/medium_chestplate_darkpink
      generate: false
      material: LEATHER_CHESTPLATE
    equipment:
      id: medieval_armor_set_medium_armor_darkpink
      legacy_armor_rendering_id: medieval_armor_set_medium_armor_darkpink
      slot: CHEST
  medieval_armor_set_medium_leggings_darkpink:
    display_name: Medium Leggings (darkpink)
    resource:
      model_id: 561
      model_path: medieval_armor_set/medium_leggings_darkpink
      generate: false
    specific_properties:
      armor:
        slot: legs
        custom_armor: medieval_armor_set_medium_armor_darkpink
  medieval_armor_set_medium_boots_darkpink:
    display_name: Medium Boots (darkpink)
    resource:
      model_id: 558
      model_path: medieval_armor_set/medium_boots_darkpink
      generate: false
      material: LEATHER_BOOTS
    equipment:
      id: medieval_armor_set_medium_armor_darkpink
      legacy_armor_rendering_id: medieval_armor_set_medium_armor_darkpink
      slot: FEET
  medieval_armor_set_wizard_helmet_darkpink:
    display_name: Wizard Helmet (darkpink)
    resource:
      model_id: 564
      model_path: medieval_armor_set/wizard_helmet_darkpink
      generate: false
      material: LEATHER_HELMET
    equipment:
      id: medieval_armor_set_wizard_armor_darkpink
      legacy_armor_rendering_id: medieval_armor_set_wizard_armor_darkpink
      slot: HEAD
  medieval_armor_set_wizard_chestplate_darkpink:
    display_name: Wizard Chestplate (darkpink)
    resource:
      model_id: 563
      model_path: medieval_armor_set/wizard_chestplate_darkpink
      generate: false
      material: LEATHER_CHESTPLATE
    equipment:
      id: medieval_armor_set_wizard_armor_darkpink
      legacy_armor_rendering_id: medieval_armor_set_wizard_armor_darkpink
      slot: CHEST
  medieval_armor_set_wizard_leggings_darkpink:
    display_name: Wizard Leggings (darkpink)
    resource:
      model_id: 565
      model_path: medieval_armor_set/wizard_leggings_darkpink
      generate: false
      material: LEATHER_LEGGINGS
    equipment:
      id: medieval_armor_set_wizard_armor_darkpink
      legacy_armor_rendering_id: medieval_armor_set_wizard_armor_darkpink
      slot: LEGS
  medieval_armor_set_wizard_boots_darkpink:
    display_name: Wizard Boots (darkpink)
    resource:
      model_id: 562
      model_path: medieval_armor_set/wizard_boots_darkpink
      generate: false
      material: LEATHER_BOOTS
    equipment:
      id: medieval_armor_set_wizard_armor_darkpink
      legacy_armor_rendering_id: medieval_armor_set_wizard_armor_darkpink
      slot: FEET
