info:
  namespace: elitecreatures
armors_rendering:
  medieval_armor_set_heavy_armor_red:
    color: '#5520c7'
    layer_1: medieval_armor_set/heavy_armor_layer_red_1
    layer_2: medieval_armor_set/heavy_armor_layer_red_2
    use_color: false
  medieval_armor_set_light_armor_red:
    color: '#5520c8'
    layer_1: medieval_armor_set/light_armor_layer_red_1
    layer_2: medieval_armor_set/light_armor_layer_red_2
    use_color: false
  medieval_armor_set_medium_armor_red:
    color: '#5520c9'
    layer_1: medieval_armor_set/medium_armor_layer_red_1
    layer_2: medieval_armor_set/medium_armor_layer_red_2
    use_color: false
  medieval_armor_set_wizard_armor_red:
    color: '#5520ca'
    layer_1: medieval_armor_set/wizard_armor_layer_red_1
    layer_2: medieval_armor_set/wizard_armor_layer_red_2
    use_color: false
equipments:
  medieval_armor_set_heavy_armor_red:
    layer_1: medieval_armor_set/heavy_armor_layer_red_1
    layer_2: medieval_armor_set/heavy_armor_layer_red_2
  medieval_armor_set_light_armor_red:
    layer_1: medieval_armor_set/light_armor_layer_red_1
    layer_2: medieval_armor_set/light_armor_layer_red_2
  medieval_armor_set_medium_armor_red:
    layer_1: medieval_armor_set/medium_armor_layer_red_1
    layer_2: medieval_armor_set/medium_armor_layer_red_2
  medieval_armor_set_wizard_armor_red:
    layer_1: medieval_armor_set/wizard_armor_layer_red_1
    layer_2: medieval_armor_set/wizard_armor_layer_red_2
items:
  medieval_armor_set_heavy_helmet_red:
    display_name: Heavy Helmet (red)
    resource:
      model_id: 504
      generate: false
      model_path: medieval_armor_set/heavy_helmet_red
      material: LEATHER_HELMET
    equipment:
      id: medieval_armor_set_heavy_armor_red
      legacy_armor_rendering_id: medieval_armor_set_heavy_armor_red
      slot: HEAD
  medieval_armor_set_heavy_chestplate_red:
    display_name: Heavy Chestplate (red)
    resource:
      model_id: 503
      model_path: medieval_armor_set/heavy_chestplate_red
      generate: false
      material: LEATHER_CHESTPLATE
    equipment:
      id: medieval_armor_set_heavy_armor_red
      legacy_armor_rendering_id: medieval_armor_set_heavy_armor_red
      slot: CHEST
  medieval_armor_set_heavy_leggings_red:
    display_name: Heavy Leggings (red)
    resource:
      model_id: 505
      model_path: medieval_armor_set/heavy_leggings_red
      generate: false
      material: LEATHER_LEGGINGS
    equipment:
      id: medieval_armor_set_heavy_armor_red
      legacy_armor_rendering_id: medieval_armor_set_heavy_armor_red
      slot: LEGS
  medieval_armor_set_heavy_boots_red:
    display_name: Heavy Boots (red)
    resource:
      model_id: 502
      model_path: medieval_armor_set/heavy_boots_red
      generate: false
      material: LEATHER_BOOTS
    equipment:
      id: medieval_armor_set_heavy_armor_red
      legacy_armor_rendering_id: medieval_armor_set_heavy_armor_red
      slot: FEET
  medieval_armor_set_light_helmet_red:
    display_name: Light Helmet (red)
    resource:
      model_id: 508
      model_path: medieval_armor_set/light_helmet_red
      generate: false
      material: LEATHER_HELMET
    equipment:
      id: medieval_armor_set_light_armor_red
      legacy_armor_rendering_id: medieval_armor_set_light_armor_red
      slot: HEAD
  medieval_armor_set_light_chestplate_red:
    display_name: Light Chestplate (red)
    resource:
      model_id: 507
      model_path: medieval_armor_set/light_chestplate_red
      generate: false
      material: LEATHER_CHESTPLATE
    equipment:
      id: medieval_armor_set_light_armor_red
      legacy_armor_rendering_id: medieval_armor_set_light_armor_red
      slot: CHEST
  medieval_armor_set_light_leggings_red:
    display_name: Light Leggings (red)
    resource:
      model_id: 509
      model_path: medieval_armor_set/light_leggings_red
      generate: false
      material: LEATHER_LEGGINGS
    equipment:
      id: medieval_armor_set_light_armor_red
      legacy_armor_rendering_id: medieval_armor_set_light_armor_red
      slot: LEGS
  medieval_armor_set_light_boots_red:
    display_name: Light Boots (red)
    resource:
      model_id: 506
      model_path: medieval_armor_set/light_boots_red
      generate: false
      material: LEATHER_BOOTS
    equipment:
      id: medieval_armor_set_light_armor_red
      legacy_armor_rendering_id: medieval_armor_set_light_armor_red
      slot: FEET
  medieval_armor_set_medium_helmet_red:
    display_name: Medium Helmet (red)
    resource:
      model_id: 512
      model_path: medieval_armor_set/medium_helmet_red
      generate: false
      material: LEATHER_HELMET
    equipment:
      id: medieval_armor_set_medium_armor_red
      legacy_armor_rendering_id: medieval_armor_set_medium_armor_red
      slot: HEAD
  medieval_armor_set_medium_chestplate_red:
    display_name: Medium Chestplate (red)
    resource:
      model_id: 511
      model_path: medieval_armor_set/medium_chestplate_red
      generate: false
      material: LEATHER_CHESTPLATE
    equipment:
      id: medieval_armor_set_medium_armor_red
      legacy_armor_rendering_id: medieval_armor_set_medium_armor_red
      slot: CHEST
  medieval_armor_set_medium_leggings_red:
    display_name: Medium Leggings (red)
    resource:
      model_id: 513
      model_path: medieval_armor_set/medium_leggings_red
      generate: false
      material: LEATHER_LEGGINGS
    equipment:
      id: medieval_armor_set_medium_armor_red
      legacy_armor_rendering_id: medieval_armor_set_medium_armor_red
      slot: LEGS
  medieval_armor_set_medium_boots_red:
    display_name: Medium Boots (red)
    resource:
      model_id: 510
      model_path: medieval_armor_set/medium_boots_red
      generate: false
      material: LEATHER_BOOTS
    equipment:
      id: medieval_armor_set_medium_armor_red
      legacy_armor_rendering_id: medieval_armor_set_medium_armor_red
      slot: FEET
  medieval_armor_set_wizard_helmet_red:
    display_name: Wizard Helmet (red)
    resource:
      model_id: 516
      model_path: medieval_armor_set/wizard_helmet_red
      generate: false
      material: LEATHER_HELMET
    equipment:
      id: medieval_armor_set_wizard_armor_red
      legacy_armor_rendering_id: medieval_armor_set_wizard_armor_red
      slot: HEAD
  medieval_armor_set_wizard_chestplate_red:
    display_name: Wizard Chestplate (red)
    resource:
      model_id: 515
      model_path: medieval_armor_set/wizard_chestplate_red
      generate: false
      material: LEATHER_CHESTPLATE
    equipment:
      id: medieval_armor_set_wizard_armor_red
      legacy_armor_rendering_id: medieval_armor_set_wizard_armor_red
      slot: CHEST
  medieval_armor_set_wizard_leggings_red:
    display_name: Wizard Leggings (red)
    resource:
      model_id: 517
      model_path: medieval_armor_set/wizard_leggings_red
      generate: false
      material: LEATHER_LEGGINGS
    equipment:
      id: medieval_armor_set_wizard_armor_red
      legacy_armor_rendering_id: medieval_armor_set_wizard_armor_red
      slot: LEGS
  medieval_armor_set_wizard_boots_red:
    display_name: Wizard Boots (red)
    resource:
      model_id: 514
      model_path: medieval_armor_set/wizard_boots_red
      generate: false
      material: LEATHER_BOOTS
    equipment:
      id: medieval_armor_set_wizard_armor_red
      legacy_armor_rendering_id: medieval_armor_set_wizard_armor_red
      slot: FEET
