info:
  namespace: elitecreatures
armors_rendering:
  medieval_armor_set_heavy_armor_yellow:
    color: '#5520df'
    layer_1: medieval_armor_set/heavy_armor_layer_yellow_1
    layer_2: medieval_armor_set/heavy_armor_layer_yellow_2
    use_color: false
  medieval_armor_set_light_armor_yellow:
    color: '#5520e0'
    layer_1: medieval_armor_set/light_armor_layer_yellow_1
    layer_2: medieval_armor_set/light_armor_layer_yellow_2
    use_color: false
  medieval_armor_set_medium_armor_yellow:
    color: '#5520e1'
    layer_1: medieval_armor_set/medium_armor_layer_yellow_1
    layer_2: medieval_armor_set/medium_armor_layer_yellow_2
    use_color: false
  medieval_armor_set_wizard_armor_yellow:
    color: '#5520e2'
    layer_1: medieval_armor_set/wizard_armor_layer_yellow_1
    layer_2: medieval_armor_set/wizard_armor_layer_yellow_2
    use_color: false
equipments:
  medieval_armor_set_heavy_armor_yellow:
    layer_1: medieval_armor_set/heavy_armor_layer_yellow_1
    layer_2: medieval_armor_set/heavy_armor_layer_yellow_2
  medieval_armor_set_light_armor_yellow:
    layer_1: medieval_armor_set/light_armor_layer_yellow_1
    layer_2: medieval_armor_set/light_armor_layer_yellow_2
  medieval_armor_set_medium_armor_yellow:
    layer_1: medieval_armor_set/medium_armor_layer_yellow_1
    layer_2: medieval_armor_set/medium_armor_layer_yellow_2
  medieval_armor_set_wizard_armor_yellow:
    layer_1: medieval_armor_set/wizard_armor_layer_yellow_1
    layer_2: medieval_armor_set/wizard_armor_layer_yellow_2
items:
  medieval_armor_set_heavy_helmet_yellow:
    display_name: Heavy Helmet (yellow)
    resource:
      model_id: 632
      generate: false
      model_path: medieval_armor_set/heavy_helmet_yellow
      material: LEATHER_HELMET
    equipment:
      id: medieval_armor_set_heavy_armor_yellow
      legacy_armor_rendering_id: medieval_armor_set_heavy_armor_yellow
      slot: HEAD
  medieval_armor_set_heavy_chestplate_yellow:
    display_name: Heavy Chestplate (yellow)
    resource:
      model_id: 631
      model_path: medieval_armor_set/heavy_chestplate_yellow
      generate: false
      material: LEATHER_CHESTPLATE
    equipment:
      id: medieval_armor_set_heavy_armor_yellow
      legacy_armor_rendering_id: medieval_armor_set_heavy_armor_yellow
      slot: CHEST
  medieval_armor_set_heavy_leggings_yellow:
    display_name: Heavy Leggings (yellow)
    resource:
      model_id: 633
      model_path: medieval_armor_set/heavy_leggings_yellow
      generate: false
      material: LEATHER_LEGGINGS
    equipment:
      id: medieval_armor_set_heavy_armor_yellow
      legacy_armor_rendering_id: medieval_armor_set_heavy_armor_yellow
      slot: LEGS
  medieval_armor_set_heavy_boots_yellow:
    display_name: Heavy Boots (yellow)
    resource:
      model_id: 630
      model_path: medieval_armor_set/heavy_boots_yellow
      generate: false
      material: LEATHER_BOOTS
    equipment:
      id: medieval_armor_set_heavy_armor_yellow
      legacy_armor_rendering_id: medieval_armor_set_heavy_armor_yellow
      slot: FEET
  medieval_armor_set_light_helmet_yellow:
    display_name: Light Helmet (yellow)
    resource:
      model_id: 636
      model_path: medieval_armor_set/light_helmet_yellow
      generate: false
      material: LEATHER_HELMET
    equipment:
      id: medieval_armor_set_light_armor_yellow
      legacy_armor_rendering_id: medieval_armor_set_light_armor_yellow
      slot: HEAD
  medieval_armor_set_light_chestplate_yellow:
    display_name: Light Chestplate (yellow)
    resource:
      model_id: 635
      model_path: medieval_armor_set/light_chestplate_yellow
      generate: false
      material: LEATHER_CHESTPLATE
    equipment:
      id: medieval_armor_set_light_armor_yellow
      legacy_armor_rendering_id: medieval_armor_set_light_armor_yellow
      slot: CHEST
  medieval_armor_set_light_leggings_yellow:
    display_name: Light Leggings (yellow)
    resource:
      model_id: 637
      model_path: medieval_armor_set/light_leggings_yellow
      generate: false
      material: LEATHER_LEGGINGS
    equipment:
      id: medieval_armor_set_light_armor_yellow
      legacy_armor_rendering_id: medieval_armor_set_light_armor_yellow
      slot: LEGS
  medieval_armor_set_light_boots_yellow:
    display_name: Light Boots (yellow)
    resource:
      model_id: 634
      model_path: medieval_armor_set/light_boots_yellow
      generate: false
      material: LEATHER_BOOTS
    equipment:
      id: medieval_armor_set_light_armor_yellow
      legacy_armor_rendering_id: medieval_armor_set_light_armor_yellow
      slot: FEET
  medieval_armor_set_medium_helmet_yellow:
    display_name: Medium Helmet (yellow)
    resource:
      model_id: 640
      model_path: medieval_armor_set/medium_helmet_yellow
      generate: false
      material: LEATHER_HELMET
    equipment:
      id: medieval_armor_set_medium_armor_yellow
      legacy_armor_rendering_id: medieval_armor_set_medium_armor_yellow
      slot: HEAD
  medieval_armor_set_medium_chestplate_yellow:
    display_name: Medium Chestplate (yellow)
    resource:
      model_id: 639
      model_path: medieval_armor_set/medium_chestplate_yellow
      generate: false
      material: LEATHER_CHESTPLATE
    equipment:
      id: medieval_armor_set_medium_armor_yellow
      legacy_armor_rendering_id: medieval_armor_set_medium_armor_yellow
      slot: CHEST
  medieval_armor_set_medium_leggings_yellow:
    display_name: Medium Leggings (yellow)
    resource:
      model_id: 641
      model_path: medieval_armor_set/medium_leggings_yellow
      generate: false
      material: LEATHER_LEGGINGS
    equipment:
      id: medieval_armor_set_medium_armor_yellow
      legacy_armor_rendering_id: medieval_armor_set_medium_armor_yellow
      slot: LEGS
  medieval_armor_set_medium_boots_yellow:
    display_name: Medium Boots (yellow)
    resource:
      model_id: 638
      model_path: medieval_armor_set/medium_boots_yellow
      generate: false
      material: LEATHER_BOOTS
    equipment:
      id: medieval_armor_set_medium_armor_yellow
      legacy_armor_rendering_id: medieval_armor_set_medium_armor_yellow
      slot: FEET
  medieval_armor_set_wizard_helmet_yellow:
    display_name: Wizard Helmet (yellow)
    resource:
      model_id: 644
      model_path: medieval_armor_set/wizard_helmet_yellow
      generate: false
      material: LEATHER_HELMET
    equipment:
      id: medieval_armor_set_wizard_armor_yellow
      legacy_armor_rendering_id: medieval_armor_set_wizard_armor_yellow
      slot: HEAD
  medieval_armor_set_wizard_chestplate_yellow:
    display_name: Wizard Chestplate (yellow)
    resource:
      model_id: 643
      model_path: medieval_armor_set/wizard_chestplate_yellow
      generate: false
      material: LEATHER_CHESTPLATE
    equipment:
      id: medieval_armor_set_wizard_armor_yellow
      legacy_armor_rendering_id: medieval_armor_set_wizard_armor_yellow
      slot: CHEST
  medieval_armor_set_wizard_leggings_yellow:
    display_name: Wizard Leggings (yellow)
    resource:
      model_id: 645
      model_path: medieval_armor_set/wizard_leggings_yellow
      generate: false
      material: LEATHER_LEGGINGS
    equipment:
      id: medieval_armor_set_wizard_armor_yellow
      legacy_armor_rendering_id: medieval_armor_set_wizard_armor_yellow
      slot: LEGS
  medieval_armor_set_wizard_boots_yellow:
    display_name: Wizard Boots (yellow)
    resource:
      model_id: 642
      model_path: medieval_armor_set/wizard_boots_yellow
      generate: false
      material: LEATHER_BOOTS
    equipment:
      id: medieval_armor_set_wizard_armor_yellow
      legacy_armor_rendering_id: medieval_armor_set_wizard_armor_yellow
      slot: FEET
