info:
  namespace: elitecreatures
armors_rendering:
  medieval_armor_set_heavy_armor_purple:
    color: '#5520db'
    layer_1: medieval_armor_set/heavy_armor_layer_purple_1
    layer_2: medieval_armor_set/heavy_armor_layer_purple_2
    use_color: false
  medieval_armor_set_light_armor_purple:
    color: '#5520dc'
    layer_1: medieval_armor_set/light_armor_layer_purple_1
    layer_2: medieval_armor_set/light_armor_layer_purple_2
    use_color: false
  medieval_armor_set_medium_armor_purple:
    color: '#5520dd'
    layer_1: medieval_armor_set/medium_armor_layer_purple_1
    layer_2: medieval_armor_set/medium_armor_layer_purple_2
    use_color: false
  medieval_armor_set_wizard_armor_purple:
    color: '#5520de'
    layer_1: medieval_armor_set/wizard_armor_layer_purple_1
    layer_2: medieval_armor_set/wizard_armor_layer_purple_2
    use_color: false
equipments:
  medieval_armor_set_heavy_armor_purple:
    layer_1: medieval_armor_set/heavy_armor_layer_purple_1
    layer_2: medieval_armor_set/heavy_armor_layer_purple_2
  medieval_armor_set_light_armor_purple:
    layer_1: medieval_armor_set/light_armor_layer_purple_1
    layer_2: medieval_armor_set/light_armor_layer_purple_2
  medieval_armor_set_medium_armor_purple:
    layer_1: medieval_armor_set/medium_armor_layer_purple_1
    layer_2: medieval_armor_set/medium_armor_layer_purple_2
  medieval_armor_set_wizard_armor_purple:
    layer_1: medieval_armor_set/wizard_armor_layer_purple_1
    layer_2: medieval_armor_set/wizard_armor_layer_purple_2
items:
  medieval_armor_set_heavy_helmet_purple:
    display_name: Heavy Helmet (purple)
    resource:
      model_id: 808
      generate: false
      model_path: medieval_armor_set/heavy_helmet_purple
      material: LEATHER_HELMET
    equipment:
      id: medieval_armor_set_heavy_armor_purple
      legacy_armor_rendering_id: medieval_armor_set_heavy_armor_purple
      slot: HEAD
  medieval_armor_set_heavy_chestplate_purple:
    display_name: Heavy Chestplate (purple)
    resource:
      model_id: 807
      model_path: medieval_armor_set/heavy_chestplate_purple
      generate: false
      material: LEATHER_CHESTPLATE
    equipment:
      id: medieval_armor_set_heavy_armor_purple
      legacy_armor_rendering_id: medieval_armor_set_heavy_armor_purple
      slot: CHEST
  medieval_armor_set_heavy_leggings_purple:
    display_name: Heavy Leggings (purple)
    resource:
      model_id: 809
      model_path: medieval_armor_set/heavy_leggings_purple
      generate: false
      material: LEATHER_LEGGINGS
    equipment:
      id: medieval_armor_set_heavy_armor_purple
      legacy_armor_rendering_id: medieval_armor_set_heavy_armor_purple
      slot: LEGS
  medieval_armor_set_heavy_boots_purple:
    display_name: Heavy Boots (purple)
    resource:
      model_id: 806
      model_path: medieval_armor_set/heavy_boots_purple
      generate: false
      material: LEATHER_BOOTS
    equipment:
      id: medieval_armor_set_heavy_armor_purple
      legacy_armor_rendering_id: medieval_armor_set_heavy_armor_purple
      slot: FEET
  medieval_armor_set_light_helmet_purple:
    display_name: Light Helmet (purple)
    resource:
      model_id: 812
      model_path: medieval_armor_set/light_helmet_purple
      generate: false
      material: LEATHER_HELMET
    equipment:
      id: medieval_armor_set_light_armor_purple
      legacy_armor_rendering_id: medieval_armor_set_light_armor_purple
      slot: HEAD
  medieval_armor_set_light_chestplate_purple:
    display_name: Light Chestplate (purple)
    resource:
      model_id: 811
      model_path: medieval_armor_set/light_chestplate_purple
      generate: false
      material: LEATHER_CHESTPLATE
    equipment:
      id: medieval_armor_set_light_armor_purple
      legacy_armor_rendering_id: medieval_armor_set_light_armor_purple
      slot: CHEST
  medieval_armor_set_light_leggings_purple:
    display_name: Light Leggings (purple)
    resource:
      model_id: 813
      model_path: medieval_armor_set/light_leggings_purple
      generate: false
      material: LEATHER_LEGGINGS
    equipment:
      id: medieval_armor_set_light_armor_purple
      legacy_armor_rendering_id: medieval_armor_set_light_armor_purple
      slot: LEGS
  medieval_armor_set_light_boots_purple:
    display_name: Light Boots (purple)
    resource:
      model_id: 810
      model_path: medieval_armor_set/light_boots_purple
      generate: false
      material: LEATHER_BOOTS
    equipment:
      id: medieval_armor_set_light_armor_purple
      legacy_armor_rendering_id: medieval_armor_set_light_armor_purple
      slot: FEET
  medieval_armor_set_medium_helmet_purple:
    display_name: Medium Helmet (purple)
    resource:
      model_id: 816
      model_path: medieval_armor_set/medium_helmet_purple
      generate: false
      material: LEATHER_HELMET
    equipment:
      id: medieval_armor_set_medium_armor_purple
      legacy_armor_rendering_id: medieval_armor_set_medium_armor_purple
      slot: HEAD
  medieval_armor_set_medium_chestplate_purple:
    display_name: Medium Chestplate (purple)
    resource:
      model_id: 815
      model_path: medieval_armor_set/medium_chestplate_purple
      generate: false
      material: LEATHER_CHESTPLATE
    equipment:
      id: medieval_armor_set_medium_armor_purple
      legacy_armor_rendering_id: medieval_armor_set_medium_armor_purple
      slot: CHEST
  medieval_armor_set_medium_leggings_purple:
    display_name: Medium Leggings (purple)
    resource:
      model_id: 817
      model_path: medieval_armor_set/medium_leggings_purple
      generate: false
      material: LEATHER_LEGGINGS
    equipment:
      id: medieval_armor_set_medium_armor_purple
      legacy_armor_rendering_id: medieval_armor_set_medium_armor_purple
      slot: LEGS
  medieval_armor_set_medium_boots_purple:
    display_name: Medium Boots (purple)
    resource:
      model_id: 814
      model_path: medieval_armor_set/medium_boots_purple
      generate: false
      material: LEATHER_BOOTS
    equipment:
      id: medieval_armor_set_medium_armor_purple
      legacy_armor_rendering_id: medieval_armor_set_medium_armor_purple
      slot: FEET
  medieval_armor_set_wizard_helmet_purple:
    display_name: Wizard Helmet (purple)
    resource:
      model_id: 820
      model_path: medieval_armor_set/wizard_helmet_purple
      generate: false
      material: LEATHER_HELMET
    equipment:
      id: medieval_armor_set_wizard_armor_purple
      legacy_armor_rendering_id: medieval_armor_set_wizard_armor_purple
      slot: HEAD
  medieval_armor_set_wizard_chestplate_purple:
    display_name: Wizard Chestplate (purple)
    resource:
      model_id: 819
      model_path: medieval_armor_set/wizard_chestplate_purple
      generate: false
      material: LEATHER_CHESTPLATE
    equipment:
      id: medieval_armor_set_wizard_armor_purple
      legacy_armor_rendering_id: medieval_armor_set_wizard_armor_purple
      slot: CHEST
  medieval_armor_set_wizard_leggings_purple:
    display_name: Wizard Leggings (purple)
    resource:
      model_id: 821
      model_path: medieval_armor_set/wizard_leggings_purple
      generate: false
      material: LEATHER_LEGGINGS
    equipment:
      id: medieval_armor_set_wizard_armor_purple
      legacy_armor_rendering_id: medieval_armor_set_wizard_armor_purple
      slot: LEGS
  medieval_armor_set_wizard_boots_purple:
    display_name: Wizard Boots (purple)
    resource:
      model_id: 818
      model_path: medieval_armor_set/wizard_boots_purple
      generate: false
      material: LEATHER_BOOTS
    equipment:
      id: medieval_armor_set_wizard_armor_purple
      legacy_armor_rendering_id: medieval_armor_set_wizard_armor_purple
      slot: FEET
